package mnj.ont.model.services.common;

import oracle.jbo.ApplicationModule;
import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jan 20 12:16:47 PKT 2016
// ---------------------------------------------------------------------
public interface MainAM extends ApplicationModule {


    String getPopulateValue(Row r, String columnName);


    void FillBpoHeader();

    void popupDeselectActionListener();

    void populateTracking(String TrackingNum);

    void setSessionValues(String orgId, String userId, String respId,
                          String respAppl);

    void getUnitName();

    void cargoHandOverDateValidation();

    void saveBtnAction();

    void populateBalancePerPcs();

    void populateTrackingInfo();
}
