package mnj.ont.model.lov.views;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Nov 25 17:30:21 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FillBpoVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        DivisionId {
            public Object get(FillBpoVORowImpl obj) {
                return obj.getDivisionId();
            }

            public void put(FillBpoVORowImpl obj, Object value) {
                obj.setDivisionId((String)value);
            }
        }
        ,
        PackList {
            public Object get(FillBpoVORowImpl obj) {
                return obj.getPackList();
            }

            public void put(FillBpoVORowImpl obj, Object value) {
                obj.setPackList((Number)value);
            }
        }
        ,
        CustId {
            public Object get(FillBpoVORowImpl obj) {
                return obj.getCustId();
            }

            public void put(FillBpoVORowImpl obj, Object value) {
                obj.setCustId((Number)value);
            }
        }
        ,
        Style {
            public Object get(FillBpoVORowImpl obj) {
                return obj.getStyle();
            }

            public void put(FillBpoVORowImpl obj, Object value) {
                obj.setStyle((String)value);
            }
        }
        ,
        StyleNumber {
            public Object get(FillBpoVORowImpl obj) {
                return obj.getStyleNumber();
            }

            public void put(FillBpoVORowImpl obj, Object value) {
                obj.setStyleNumber((String)value);
            }
        }
        ,
        CurrentStyle {
            public Object get(FillBpoVORowImpl obj) {
                return obj.getCurrentStyle();
            }

            public void put(FillBpoVORowImpl obj, Object value) {
                obj.setCurrentStyle((String)value);
            }
        }
        ,
        Season {
            public Object get(FillBpoVORowImpl obj) {
                return obj.getSeason();
            }

            public void put(FillBpoVORowImpl obj, Object value) {
                obj.setSeason((String)value);
            }
        }
        ,
        BpoNumber {
            public Object get(FillBpoVORowImpl obj) {
                return obj.getBpoNumber();
            }

            public void put(FillBpoVORowImpl obj, Object value) {
                obj.setBpoNumber((String)value);
            }
        }
        ,
        BuyerName {
            public Object get(FillBpoVORowImpl obj) {
                return obj.getBuyerName();
            }

            public void put(FillBpoVORowImpl obj, Object value) {
                obj.setBuyerName((String)value);
            }
        }
        ,
        Description {
            public Object get(FillBpoVORowImpl obj) {
                return obj.getDescription();
            }

            public void put(FillBpoVORowImpl obj, Object value) {
                obj.setDescription((String)value);
            }
        }
        ,
        Country {
            public Object get(FillBpoVORowImpl obj) {
                return obj.getCountry();
            }

            public void put(FillBpoVORowImpl obj, Object value) {
                obj.setCountry((String)value);
            }
        }
        ,
        Dcpo {
            public Object get(FillBpoVORowImpl obj) {
                return obj.getDcpo();
            }

            public void put(FillBpoVORowImpl obj, Object value) {
                obj.setDcpo((String)value);
            }
        }
        ,
        DeliveryNumber {
            public Object get(FillBpoVORowImpl obj) {
                return obj.getDeliveryNumber();
            }

            public void put(FillBpoVORowImpl obj, Object value) {
                obj.setDeliveryNumber((String)value);
            }
        }
        ,
        ShipMode {
            public Object get(FillBpoVORowImpl obj) {
                return obj.getShipMode();
            }

            public void put(FillBpoVORowImpl obj, Object value) {
                obj.setShipMode((String)value);
            }
        }
        ,
        ShipCancelExBdDate {
            public Object get(FillBpoVORowImpl obj) {
                return obj.getShipCancelExBdDate();
            }

            public void put(FillBpoVORowImpl obj, Object value) {
                obj.setShipCancelExBdDate((Date)value);
            }
        }
        ,
        ShipExFactoryDate {
            public Object get(FillBpoVORowImpl obj) {
                return obj.getShipExFactoryDate();
            }

            public void put(FillBpoVORowImpl obj, Object value) {
                obj.setShipExFactoryDate((Date)value);
            }
        }
        ,
        InvoiceNo {
            public Object get(FillBpoVORowImpl obj) {
                return obj.getInvoiceNo();
            }

            public void put(FillBpoVORowImpl obj, Object value) {
                obj.setInvoiceNo((String)value);
            }
        }
        ,
        PackedPcsQty {
            public Object get(FillBpoVORowImpl obj) {
                return obj.getPackedPcsQty();
            }

            public void put(FillBpoVORowImpl obj, Object value) {
                obj.setPackedPcsQty((Number)value);
            }
        }
        ,
        PackedCartonQty {
            public Object get(FillBpoVORowImpl obj) {
                return obj.getPackedCartonQty();
            }

            public void put(FillBpoVORowImpl obj, Object value) {
                obj.setPackedCartonQty((Number)value);
            }
        }
        ,
        CbmTotal {
            public Object get(FillBpoVORowImpl obj) {
                return obj.getCbmTotal();
            }

            public void put(FillBpoVORowImpl obj, Object value) {
                obj.setCbmTotal((Number)value);
            }
        }
        ,
        AssignedPcs {
            public Object get(FillBpoVORowImpl obj) {
                return obj.getAssignedPcs();
            }

            public void put(FillBpoVORowImpl obj, Object value) {
                obj.setAssignedPcs((Number)value);
            }
        }
        ,
        AssignedCarton {
            public Object get(FillBpoVORowImpl obj) {
                return obj.getAssignedCarton();
            }

            public void put(FillBpoVORowImpl obj, Object value) {
                obj.setAssignedCarton((Number)value);
            }
        }
        ,
        AssignedCbm {
            public Object get(FillBpoVORowImpl obj) {
                return obj.getAssignedCbm();
            }

            public void put(FillBpoVORowImpl obj, Object value) {
                obj.setAssignedCbm((Number)value);
            }
        }
        ,
        BalancePcsQty {
            public Object get(FillBpoVORowImpl obj) {
                return obj.getBalancePcsQty();
            }

            public void put(FillBpoVORowImpl obj, Object value) {
                obj.setBalancePcsQty((Number)value);
            }
        }
        ,
        BalanceCartonQty {
            public Object get(FillBpoVORowImpl obj) {
                return obj.getBalanceCartonQty();
            }

            public void put(FillBpoVORowImpl obj, Object value) {
                obj.setBalanceCartonQty((Number)value);
            }
        }
        ,
        BalanceCbm {
            public Object get(FillBpoVORowImpl obj) {
                return obj.getBalanceCbm();
            }

            public void put(FillBpoVORowImpl obj, Object value) {
                obj.setBalanceCbm((Number)value);
            }
        }
        ,
        TotalCbm {
            public Object get(FillBpoVORowImpl obj) {
                return obj.getTotalCbm();
            }

            public void put(FillBpoVORowImpl obj, Object value) {
                obj.setTotalCbm((Number)value);
            }
        }
        ,
        FlagNew {
            public Object get(FillBpoVORowImpl obj) {
                return obj.getFlagNew();
            }

            public void put(FillBpoVORowImpl obj, Object value) {
                obj.setFlagNew((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;


        private static int firstIndex = 0;

        public abstract Object get(FillBpoVORowImpl object);

        public abstract void put(FillBpoVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int DIVISIONID = AttributesEnum.DivisionId.index();
    public static final int PACKLIST = AttributesEnum.PackList.index();
    public static final int CUSTID = AttributesEnum.CustId.index();
    public static final int STYLE = AttributesEnum.Style.index();
    public static final int STYLENUMBER = AttributesEnum.StyleNumber.index();
    public static final int CURRENTSTYLE = AttributesEnum.CurrentStyle.index();
    public static final int SEASON = AttributesEnum.Season.index();
    public static final int BPONUMBER = AttributesEnum.BpoNumber.index();
    public static final int BUYERNAME = AttributesEnum.BuyerName.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int COUNTRY = AttributesEnum.Country.index();
    public static final int DCPO = AttributesEnum.Dcpo.index();
    public static final int DELIVERYNUMBER = AttributesEnum.DeliveryNumber.index();
    public static final int SHIPMODE = AttributesEnum.ShipMode.index();
    public static final int SHIPCANCELEXBDDATE = AttributesEnum.ShipCancelExBdDate.index();
    public static final int SHIPEXFACTORYDATE = AttributesEnum.ShipExFactoryDate.index();
    public static final int INVOICENO = AttributesEnum.InvoiceNo.index();
    public static final int PACKEDPCSQTY = AttributesEnum.PackedPcsQty.index();
    public static final int PACKEDCARTONQTY = AttributesEnum.PackedCartonQty.index();
    public static final int CBMTOTAL = AttributesEnum.CbmTotal.index();
    public static final int ASSIGNEDPCS = AttributesEnum.AssignedPcs.index();
    public static final int ASSIGNEDCARTON = AttributesEnum.AssignedCarton.index();
    public static final int ASSIGNEDCBM = AttributesEnum.AssignedCbm.index();
    public static final int BALANCEPCSQTY = AttributesEnum.BalancePcsQty.index();
    public static final int BALANCECARTONQTY = AttributesEnum.BalanceCartonQty.index();
    public static final int BALANCECBM = AttributesEnum.BalanceCbm.index();
    public static final int TOTALCBM = AttributesEnum.TotalCbm.index();
    public static final int FLAGNEW = AttributesEnum.FlagNew.index();

    /**
     * This is the default constructor (do not remove).
     */
    public FillBpoVORowImpl() {
    }


    /**
     * Gets the attribute value for the calculated attribute CustId.
     * @return the CustId
     */
    public Number getCustId() {
        return (Number) getAttributeInternal(CUSTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CustId.
     * @param value value to set the  CustId
     */
    public void setCustId(Number value) {
        setAttributeInternal(CUSTID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Style.
     * @return the Style
     */
    public String getStyle() {
        return (String) getAttributeInternal(STYLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Style.
     * @param value value to set the  Style
     */
    public void setStyle(String value) {
        setAttributeInternal(STYLE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute StyleNumber.
     * @return the StyleNumber
     */
    public String getStyleNumber() {
        return (String) getAttributeInternal(STYLENUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute StyleNumber.
     * @param value value to set the  StyleNumber
     */
    public void setStyleNumber(String value) {
        setAttributeInternal(STYLENUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CurrentStyle.
     * @return the CurrentStyle
     */
    public String getCurrentStyle() {
        return (String) getAttributeInternal(CURRENTSTYLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CurrentStyle.
     * @param value value to set the  CurrentStyle
     */
    public void setCurrentStyle(String value) {
        setAttributeInternal(CURRENTSTYLE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Season.
     * @return the Season
     */
    public String getSeason() {
        return (String) getAttributeInternal(SEASON);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Season.
     * @param value value to set the  Season
     */
    public void setSeason(String value) {
        setAttributeInternal(SEASON, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BpoNumber.
     * @return the BpoNumber
     */
    public String getBpoNumber() {
        return (String) getAttributeInternal(BPONUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BpoNumber.
     * @param value value to set the  BpoNumber
     */
    public void setBpoNumber(String value) {
        setAttributeInternal(BPONUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BuyerName.
     * @return the BuyerName
     */
    public String getBuyerName() {
        return (String) getAttributeInternal(BUYERNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BuyerName.
     * @param value value to set the  BuyerName
     */
    public void setBuyerName(String value) {
        setAttributeInternal(BUYERNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Description.
     * @return the Description
     */
    public String getDescription() {
        return (String) getAttributeInternal(DESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Description.
     * @param value value to set the  Description
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DeliveryNumber.
     * @return the DeliveryNumber
     */
    public String getDeliveryNumber() {
        return (String) getAttributeInternal(DELIVERYNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DeliveryNumber.
     * @param value value to set the  DeliveryNumber
     */
    public void setDeliveryNumber(String value) {
        setAttributeInternal(DELIVERYNUMBER, value);
    }

  

    /**
     * Gets the attribute value for the calculated attribute Country.
     * @return the Country
     */
    public String getCountry() {
        return (String) getAttributeInternal(COUNTRY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Country.
     * @param value value to set the  Country
     */
    public void setCountry(String value) {
        setAttributeInternal(COUNTRY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Dcpo.
     * @return the Dcpo
     */
    public String getDcpo() {
        return (String) getAttributeInternal(DCPO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Dcpo.
     * @param value value to set the  Dcpo
     */
    public void setDcpo(String value) {
        setAttributeInternal(DCPO, value);
    }

   

    /**
     * Gets the attribute value for the calculated attribute ShipCancelExBdDate.
     * @return the ShipCancelExBdDate
     */
    public Date getShipCancelExBdDate() {
        return (Date) getAttributeInternal(SHIPCANCELEXBDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ShipCancelExBdDate.
     * @param value value to set the  ShipCancelExBdDate
     */
    public void setShipCancelExBdDate(Date value) {
        setAttributeInternal(SHIPCANCELEXBDDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ShipExFactoryDate.
     * @return the ShipExFactoryDate
     */
    public Date getShipExFactoryDate() {
        return (Date) getAttributeInternal(SHIPEXFACTORYDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ShipExFactoryDate.
     * @param value value to set the  ShipExFactoryDate
     */
    public void setShipExFactoryDate(Date value) {
        setAttributeInternal(SHIPEXFACTORYDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ShipMode.
     * @return the ShipMode
     */
    public String getShipMode() {
        return (String) getAttributeInternal(SHIPMODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ShipMode.
     * @param value value to set the  ShipMode
     */
    public void setShipMode(String value) {
        setAttributeInternal(SHIPMODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CbmTotal.
     * @return the CbmTotal
     */
    public Number getCbmTotal() {
        return (Number) getAttributeInternal(CBMTOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CbmTotal.
     * @param value value to set the  CbmTotal
     */
    public void setCbmTotal(Number value) {
        setAttributeInternal(CBMTOTAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute InvoiceNo.
     * @return the InvoiceNo
     */
    public String getInvoiceNo() {
        return (String) getAttributeInternal(INVOICENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute InvoiceNo.
     * @param value value to set the  InvoiceNo
     */
    public void setInvoiceNo(String value) {
        setAttributeInternal(INVOICENO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PackedPcsQty.
     * @return the PackedPcsQty
     */
    public Number getPackedPcsQty() {
        return (Number) getAttributeInternal(PACKEDPCSQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PackedPcsQty.
     * @param value value to set the  PackedPcsQty
     */
    public void setPackedPcsQty(Number value) {
        setAttributeInternal(PACKEDPCSQTY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PackedCartonQty.
     * @return the PackedCartonQty
     */
    public Number getPackedCartonQty() {
        return (Number) getAttributeInternal(PACKEDCARTONQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PackedCartonQty.
     * @param value value to set the  PackedCartonQty
     */
    public void setPackedCartonQty(Number value) {
        setAttributeInternal(PACKEDCARTONQTY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DivisionId.
     * @return the DivisionId
     */
    public String getDivisionId() {
        return (String) getAttributeInternal(DIVISIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DivisionId.
     * @param value value to set the  DivisionId
     */
    public void setDivisionId(String value) {
        setAttributeInternal(DIVISIONID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PackList.
     * @return the PackList
     */
    public Number getPackList() {
        return (Number) getAttributeInternal(PACKLIST);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PackList.
     * @param value value to set the  PackList
     */
    public void setPackList(Number value) {
        setAttributeInternal(PACKLIST, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BalanceCbm.
     * @return the BalanceCbm
     */
    public Number getBalanceCbm() {
        return (Number) getAttributeInternal(BALANCECBM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BalanceCbm.
     * @param value value to set the  BalanceCbm
     */
    public void setBalanceCbm(Number value) {
        setAttributeInternal(BALANCECBM, value);
    }

    /**
     * Gets the attribute value for the calculated attribute AssignedPcs.
     * @return the AssignedPcs
     */
    public Number getAssignedPcs() {
        return (Number) getAttributeInternal(ASSIGNEDPCS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AssignedPcs.
     * @param value value to set the  AssignedPcs
     */
    public void setAssignedPcs(Number value) {
        setAttributeInternal(ASSIGNEDPCS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute AssignedCarton.
     * @return the AssignedCarton
     */
    public Number getAssignedCarton() {
        return (Number) getAttributeInternal(ASSIGNEDCARTON);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AssignedCarton.
     * @param value value to set the  AssignedCarton
     */
    public void setAssignedCarton(Number value) {
        setAttributeInternal(ASSIGNEDCARTON, value);
    }

    /**
     * Gets the attribute value for the calculated attribute AssignedCbm.
     * @return the AssignedCbm
     */
    public Number getAssignedCbm() {
        return (Number) getAttributeInternal(ASSIGNEDCBM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AssignedCbm.
     * @param value value to set the  AssignedCbm
     */
    public void setAssignedCbm(Number value) {
        setAttributeInternal(ASSIGNEDCBM, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BalancePcsQty.
     * @return the BalancePcsQty
     */
    public Number getBalancePcsQty() {
        return (Number) getAttributeInternal(BALANCEPCSQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BalancePcsQty.
     * @param value value to set the  BalancePcsQty
     */
    public void setBalancePcsQty(Number value) {
        setAttributeInternal(BALANCEPCSQTY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BalanceCartonQty.
     * @return the BalanceCartonQty
     */
    public Number getBalanceCartonQty() {
        return (Number) getAttributeInternal(BALANCECARTONQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BalanceCartonQty.
     * @param value value to set the  BalanceCartonQty
     */
    public void setBalanceCartonQty(Number value) {
        setAttributeInternal(BALANCECARTONQTY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TotalCbm.
     * @return the TotalCbm
     */
    public Number getTotalCbm() {
        return (Number) getAttributeInternal(TOTALCBM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TotalCbm.
     * @param value value to set the  TotalCbm
     */
    public void setTotalCbm(Number value) {
        setAttributeInternal(TOTALCBM, value);
    }

    /**
     * Gets the attribute value for the calculated attribute FlagNew.
     * @return the FlagNew
     */
    public String getFlagNew() {
        return (String) getAttributeInternal(FLAGNEW);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute FlagNew.
     * @param value value to set the  FlagNew
     */
    public void setFlagNew(String value) {
        setAttributeInternal(FLAGNEW, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
