package mnj.ont.model.lov.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Nov 25 17:13:15 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class transpotationVoImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public transpotationVoImpl() {
    }
}
