package mnj.ont.model.lov;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Nov 26 15:47:10 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class StatusLovVoImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public StatusLovVoImpl() {
    }
}
