package mnj.ont.model.services.client;

import mnj.ont.model.services.common.MainAM;

import oracle.jbo.Row;
import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jan 20 12:16:47 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MainAMClient extends ApplicationModuleImpl implements MainAM {
    /**
     * This is the default constructor (do not remove).
     */
    public MainAMClient() {
    }

    public void populateExpInlandLines1(String OrgId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"populateExpInlandLines1",new String [] {"java.lang.String"},new Object[] {OrgId});
        return;
    }

    public void populateExpInlandLines(Row poprow) {
        Object _ret =
            this.riInvokeExportedMethod(this,"populateExpInlandLines",new String [] {"oracle.jbo.Row"},new Object[] {poprow});
        return;
    }


    public Row createExpInlandLines() {
        Object _ret =
            this.riInvokeExportedMethod(this,"createExpInlandLines",null,null);
        return (Row)_ret;
    }

    public void callExpInlandFetch() {
        Object _ret =
            this.riInvokeExportedMethod(this,"callExpInlandFetch",null,null);
        return;
    }


    public String getPopulateValue(Row r, String columnName) {
        Object _ret =
            this.riInvokeExportedMethod(this,"getPopulateValue",new String [] {"oracle.jbo.Row","java.lang.String"},new Object[] {r, columnName});
        return (String)_ret;
    }

    public void FillBpoHeader() {
        Object _ret = this.riInvokeExportedMethod(this,"FillBpoHeader",null,null);
        return;
    }

    public void popupDeselectActionListener() {
        Object _ret =
            this.riInvokeExportedMethod(this,"popupDeselectActionListener",null,null);
        return;
    }

    public void populateTracking(String TrackingNum) {
        Object _ret =
            this.riInvokeExportedMethod(this,"populateTracking",new String [] {"java.lang.String"},new Object[] {TrackingNum});
        return;
    }

    public void setSessionValues(String orgId, String userId, String respId,
                                 String respAppl) {
        Object _ret =
            this.riInvokeExportedMethod(this,"setSessionValues",new String [] {"java.lang.String","java.lang.String","java.lang.String","java.lang.String"},new Object[] {orgId, userId, respId, respAppl});
        return;
    }

    public void getUnitName() {
        Object _ret = this.riInvokeExportedMethod(this,"getUnitName",null,null);
        return;
    }

    public void cargoHandOverDateValidation() {
        Object _ret =
            this.riInvokeExportedMethod(this,"cargoHandOverDateValidation",null,null);
        return;
    }

    public void saveBtnAction() {
        Object _ret = this.riInvokeExportedMethod(this,"saveBtnAction",null,null);
        return;
    }

    public void populateBalancePerPcs() {
        Object _ret =
            this.riInvokeExportedMethod(this,"populateBalancePerPcs",null,null);
        return;
    }

    public void populateTrackingInfo() {
        Object _ret =
            this.riInvokeExportedMethod(this,"populateTrackingInfo",null,null);
        return;
    }
}
