package mnj.ont.model.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jan 18 13:27:09 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FillExpInlandTransportImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public FillExpInlandTransportImpl() {
    }
}
