package mnj.ont.model.views;

import java.sql.ResultSet;

import oracle.jbo.server.ViewObjectImpl;
import oracle.jbo.server.ViewRowImpl;
import oracle.jbo.server.ViewRowSetImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Aug 10 10:20:39 BDT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InlandTransportLinesVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public InlandTransportLinesVOImpl() {
    }


}
