package mnj.ont.model.entities;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Nov 26 15:26:03 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CommercalTabEoImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        InlandCommercialId {
            public Object get(CommercalTabEoImpl obj) {
                return obj.getInlandCommercialId();
            }

            public void put(CommercalTabEoImpl obj, Object value) {
                obj.setInlandCommercialId((Number)value);
            }
        }
        ,
        InlandTransHeaderId {
            public Object get(CommercalTabEoImpl obj) {
                return obj.getInlandTransHeaderId();
            }

            public void put(CommercalTabEoImpl obj, Object value) {
                obj.setInlandTransHeaderId((Number)value);
            }
        }
        ,
        CargoUnloadingDate {
            public Object get(CommercalTabEoImpl obj) {
                return obj.getCargoUnloadingDate();
            }

            public void put(CommercalTabEoImpl obj, Object value) {
                obj.setCargoUnloadingDate((Date)value);
            }
        }
        ,
        CargoHandoverDate {
            public Object get(CommercalTabEoImpl obj) {
                return obj.getCargoHandoverDate();
            }

            public void put(CommercalTabEoImpl obj, Object value) {
                obj.setCargoHandoverDate((Date)value);
            }
        }
        ,
        LastUpdateLogin {
            public Object get(CommercalTabEoImpl obj) {
                return obj.getLastUpdateLogin();
            }

            public void put(CommercalTabEoImpl obj, Object value) {
                obj.setLastUpdateLogin((Number)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(CommercalTabEoImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(CommercalTabEoImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(CommercalTabEoImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(CommercalTabEoImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(CommercalTabEoImpl obj) {
                return obj.getCreationDate();
            }

            public void put(CommercalTabEoImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(CommercalTabEoImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(CommercalTabEoImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        Attribute1 {
            public Object get(CommercalTabEoImpl obj) {
                return obj.getAttribute1();
            }

            public void put(CommercalTabEoImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(CommercalTabEoImpl obj) {
                return obj.getAttribute2();
            }

            public void put(CommercalTabEoImpl obj, Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(CommercalTabEoImpl obj) {
                return obj.getAttribute3();
            }

            public void put(CommercalTabEoImpl obj, Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(CommercalTabEoImpl obj) {
                return obj.getAttribute4();
            }

            public void put(CommercalTabEoImpl obj, Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(CommercalTabEoImpl obj) {
                return obj.getAttribute5();
            }

            public void put(CommercalTabEoImpl obj, Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(CommercalTabEoImpl obj) {
                return obj.getAttribute6();
            }

            public void put(CommercalTabEoImpl obj, Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(CommercalTabEoImpl obj) {
                return obj.getAttribute7();
            }

            public void put(CommercalTabEoImpl obj, Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(CommercalTabEoImpl obj) {
                return obj.getAttribute8();
            }

            public void put(CommercalTabEoImpl obj, Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(CommercalTabEoImpl obj) {
                return obj.getAttribute9();
            }

            public void put(CommercalTabEoImpl obj, Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        AttributeNum1 {
            public Object get(CommercalTabEoImpl obj) {
                return obj.getAttributeNum1();
            }

            public void put(CommercalTabEoImpl obj, Object value) {
                obj.setAttributeNum1((Number)value);
            }
        }
        ,
        AttributeNum2 {
            public Object get(CommercalTabEoImpl obj) {
                return obj.getAttributeNum2();
            }

            public void put(CommercalTabEoImpl obj, Object value) {
                obj.setAttributeNum2((Number)value);
            }
        }
        ,
        AttributeNum3 {
            public Object get(CommercalTabEoImpl obj) {
                return obj.getAttributeNum3();
            }

            public void put(CommercalTabEoImpl obj, Object value) {
                obj.setAttributeNum3((Number)value);
            }
        }
        ,
        AttributeNum4 {
            public Object get(CommercalTabEoImpl obj) {
                return obj.getAttributeNum4();
            }

            public void put(CommercalTabEoImpl obj, Object value) {
                obj.setAttributeNum4((Number)value);
            }
        }
        ,
        AttributeNum5 {
            public Object get(CommercalTabEoImpl obj) {
                return obj.getAttributeNum5();
            }

            public void put(CommercalTabEoImpl obj, Object value) {
                obj.setAttributeNum5((Number)value);
            }
        }
        ,
        AttributeNum6 {
            public Object get(CommercalTabEoImpl obj) {
                return obj.getAttributeNum6();
            }

            public void put(CommercalTabEoImpl obj, Object value) {
                obj.setAttributeNum6((Number)value);
            }
        }
        ,
        AttributeNum7 {
            public Object get(CommercalTabEoImpl obj) {
                return obj.getAttributeNum7();
            }

            public void put(CommercalTabEoImpl obj, Object value) {
                obj.setAttributeNum7((Number)value);
            }
        }
        ,
        AttributeNum8 {
            public Object get(CommercalTabEoImpl obj) {
                return obj.getAttributeNum8();
            }

            public void put(CommercalTabEoImpl obj, Object value) {
                obj.setAttributeNum8((Number)value);
            }
        }
        ,
        AttributeNum9 {
            public Object get(CommercalTabEoImpl obj) {
                return obj.getAttributeNum9();
            }

            public void put(CommercalTabEoImpl obj, Object value) {
                obj.setAttributeNum9((Number)value);
            }
        }
        ,
        AttributeNum10 {
            public Object get(CommercalTabEoImpl obj) {
                return obj.getAttributeNum10();
            }

            public void put(CommercalTabEoImpl obj, Object value) {
                obj.setAttributeNum10((Number)value);
            }
        }
        ,
        AttributeDate1 {
            public Object get(CommercalTabEoImpl obj) {
                return obj.getAttributeDate1();
            }

            public void put(CommercalTabEoImpl obj, Object value) {
                obj.setAttributeDate1((Date)value);
            }
        }
        ,
        AttributeDate2 {
            public Object get(CommercalTabEoImpl obj) {
                return obj.getAttributeDate2();
            }

            public void put(CommercalTabEoImpl obj, Object value) {
                obj.setAttributeDate2((Date)value);
            }
        }
        ,
        AttributeDate3 {
            public Object get(CommercalTabEoImpl obj) {
                return obj.getAttributeDate3();
            }

            public void put(CommercalTabEoImpl obj, Object value) {
                obj.setAttributeDate3((Date)value);
            }
        }
        ,
        AttributeDate4 {
            public Object get(CommercalTabEoImpl obj) {
                return obj.getAttributeDate4();
            }

            public void put(CommercalTabEoImpl obj, Object value) {
                obj.setAttributeDate4((Date)value);
            }
        }
        ,
        AttributeDate5 {
            public Object get(CommercalTabEoImpl obj) {
                return obj.getAttributeDate5();
            }

            public void put(CommercalTabEoImpl obj, Object value) {
                obj.setAttributeDate5((Date)value);
            }
        }
        ,
        CfsName {
            public Object get(CommercalTabEoImpl obj) {
                return obj.getCfsName();
            }

            public void put(CommercalTabEoImpl obj, Object value) {
                obj.setCfsName((String)value);
            }
        }
        ,
        VehicleArrivalCfs {
            public Object get(CommercalTabEoImpl obj) {
                return obj.getVehicleArrivalCfs();
            }

            public void put(CommercalTabEoImpl obj, Object value) {
                obj.setVehicleArrivalCfs((Date)value);
            }
        }
        ,
        InlandTransportHeaderEO {
            public Object get(CommercalTabEoImpl obj) {
                return obj.getInlandTransportHeaderEO();
            }

            public void put(CommercalTabEoImpl obj, Object value) {
                obj.setInlandTransportHeaderEO((InlandTransportHeaderEOImpl)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(CommercalTabEoImpl object);

        public abstract void put(CommercalTabEoImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int INLANDCOMMERCIALID = AttributesEnum.InlandCommercialId.index();
    public static final int INLANDTRANSHEADERID = AttributesEnum.InlandTransHeaderId.index();
    public static final int CARGOUNLOADINGDATE = AttributesEnum.CargoUnloadingDate.index();
    public static final int CARGOHANDOVERDATE = AttributesEnum.CargoHandoverDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTENUM1 = AttributesEnum.AttributeNum1.index();
    public static final int ATTRIBUTENUM2 = AttributesEnum.AttributeNum2.index();
    public static final int ATTRIBUTENUM3 = AttributesEnum.AttributeNum3.index();
    public static final int ATTRIBUTENUM4 = AttributesEnum.AttributeNum4.index();
    public static final int ATTRIBUTENUM5 = AttributesEnum.AttributeNum5.index();
    public static final int ATTRIBUTENUM6 = AttributesEnum.AttributeNum6.index();
    public static final int ATTRIBUTENUM7 = AttributesEnum.AttributeNum7.index();
    public static final int ATTRIBUTENUM8 = AttributesEnum.AttributeNum8.index();
    public static final int ATTRIBUTENUM9 = AttributesEnum.AttributeNum9.index();
    public static final int ATTRIBUTENUM10 = AttributesEnum.AttributeNum10.index();
    public static final int ATTRIBUTEDATE1 = AttributesEnum.AttributeDate1.index();
    public static final int ATTRIBUTEDATE2 = AttributesEnum.AttributeDate2.index();
    public static final int ATTRIBUTEDATE3 = AttributesEnum.AttributeDate3.index();
    public static final int ATTRIBUTEDATE4 = AttributesEnum.AttributeDate4.index();
    public static final int ATTRIBUTEDATE5 = AttributesEnum.AttributeDate5.index();
    public static final int CFSNAME = AttributesEnum.CfsName.index();
    public static final int VEHICLEARRIVALCFS = AttributesEnum.VehicleArrivalCfs.index();
    public static final int INLANDTRANSPORTHEADEREO = AttributesEnum.InlandTransportHeaderEO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CommercalTabEoImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("mnj.ont.model.entities.CommercalTabEo");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for InlandCommercialId, using the alias name InlandCommercialId.
     * @return the InlandCommercialId
     */
    public Number getInlandCommercialId() {
        return (Number)getAttributeInternal(INLANDCOMMERCIALID);
    }

    /**
     * Sets <code>value</code> as the attribute value for InlandCommercialId.
     * @param value value to set the InlandCommercialId
     */
    public void setInlandCommercialId(Number value) {
        setAttributeInternal(INLANDCOMMERCIALID, value);
    }

    /**
     * Gets the attribute value for InlandTransHeaderId, using the alias name InlandTransHeaderId.
     * @return the InlandTransHeaderId
     */
    public Number getInlandTransHeaderId() {
        return (Number)getAttributeInternal(INLANDTRANSHEADERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for InlandTransHeaderId.
     * @param value value to set the InlandTransHeaderId
     */
    public void setInlandTransHeaderId(Number value) {
        setAttributeInternal(INLANDTRANSHEADERID, value);
    }

    /**
     * Gets the attribute value for CargoUnloadingDate, using the alias name CargoUnloadingDate.
     * @return the CargoUnloadingDate
     */
    public Date getCargoUnloadingDate() {
        return (Date)getAttributeInternal(CARGOUNLOADINGDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CargoUnloadingDate.
     * @param value value to set the CargoUnloadingDate
     */
    public void setCargoUnloadingDate(Date value) {
        setAttributeInternal(CARGOUNLOADINGDATE, value);
    }

    /**
     * Gets the attribute value for CargoHandoverDate, using the alias name CargoHandoverDate.
     * @return the CargoHandoverDate
     */
    public Date getCargoHandoverDate() {
        return (Date)getAttributeInternal(CARGOHANDOVERDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CargoHandoverDate.
     * @param value value to set the CargoHandoverDate
     */
    public void setCargoHandoverDate(Date value) {
        setAttributeInternal(CARGOHANDOVERDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin.
     * @return the LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number)getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateLogin.
     * @param value value to set the LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateDate.
     * @param value value to set the LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for Attribute1, using the alias name Attribute1.
     * @return the Attribute1
     */
    public String getAttribute1() {
        return (String)getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute1.
     * @param value value to set the Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for Attribute2, using the alias name Attribute2.
     * @return the Attribute2
     */
    public String getAttribute2() {
        return (String)getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute2.
     * @param value value to set the Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for Attribute3, using the alias name Attribute3.
     * @return the Attribute3
     */
    public String getAttribute3() {
        return (String)getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute3.
     * @param value value to set the Attribute3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for Attribute4, using the alias name Attribute4.
     * @return the Attribute4
     */
    public String getAttribute4() {
        return (String)getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute4.
     * @param value value to set the Attribute4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for Attribute5, using the alias name Attribute5.
     * @return the Attribute5
     */
    public String getAttribute5() {
        return (String)getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute5.
     * @param value value to set the Attribute5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for Attribute6, using the alias name Attribute6.
     * @return the Attribute6
     */
    public String getAttribute6() {
        return (String)getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute6.
     * @param value value to set the Attribute6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for Attribute7, using the alias name Attribute7.
     * @return the Attribute7
     */
    public String getAttribute7() {
        return (String)getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute7.
     * @param value value to set the Attribute7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for Attribute8, using the alias name Attribute8.
     * @return the Attribute8
     */
    public String getAttribute8() {
        return (String)getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute8.
     * @param value value to set the Attribute8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for Attribute9, using the alias name Attribute9.
     * @return the Attribute9
     */
    public String getAttribute9() {
        return (String)getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute9.
     * @param value value to set the Attribute9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for AttributeNum1, using the alias name AttributeNum1.
     * @return the AttributeNum1
     */
    public Number getAttributeNum1() {
        return (Number)getAttributeInternal(ATTRIBUTENUM1);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeNum1.
     * @param value value to set the AttributeNum1
     */
    public void setAttributeNum1(Number value) {
        setAttributeInternal(ATTRIBUTENUM1, value);
    }

    /**
     * Gets the attribute value for AttributeNum2, using the alias name AttributeNum2.
     * @return the AttributeNum2
     */
    public Number getAttributeNum2() {
        return (Number)getAttributeInternal(ATTRIBUTENUM2);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeNum2.
     * @param value value to set the AttributeNum2
     */
    public void setAttributeNum2(Number value) {
        setAttributeInternal(ATTRIBUTENUM2, value);
    }

    /**
     * Gets the attribute value for AttributeNum3, using the alias name AttributeNum3.
     * @return the AttributeNum3
     */
    public Number getAttributeNum3() {
        return (Number)getAttributeInternal(ATTRIBUTENUM3);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeNum3.
     * @param value value to set the AttributeNum3
     */
    public void setAttributeNum3(Number value) {
        setAttributeInternal(ATTRIBUTENUM3, value);
    }

    /**
     * Gets the attribute value for AttributeNum4, using the alias name AttributeNum4.
     * @return the AttributeNum4
     */
    public Number getAttributeNum4() {
        return (Number)getAttributeInternal(ATTRIBUTENUM4);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeNum4.
     * @param value value to set the AttributeNum4
     */
    public void setAttributeNum4(Number value) {
        setAttributeInternal(ATTRIBUTENUM4, value);
    }

    /**
     * Gets the attribute value for AttributeNum5, using the alias name AttributeNum5.
     * @return the AttributeNum5
     */
    public Number getAttributeNum5() {
        return (Number)getAttributeInternal(ATTRIBUTENUM5);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeNum5.
     * @param value value to set the AttributeNum5
     */
    public void setAttributeNum5(Number value) {
        setAttributeInternal(ATTRIBUTENUM5, value);
    }

    /**
     * Gets the attribute value for AttributeNum6, using the alias name AttributeNum6.
     * @return the AttributeNum6
     */
    public Number getAttributeNum6() {
        return (Number)getAttributeInternal(ATTRIBUTENUM6);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeNum6.
     * @param value value to set the AttributeNum6
     */
    public void setAttributeNum6(Number value) {
        setAttributeInternal(ATTRIBUTENUM6, value);
    }

    /**
     * Gets the attribute value for AttributeNum7, using the alias name AttributeNum7.
     * @return the AttributeNum7
     */
    public Number getAttributeNum7() {
        return (Number)getAttributeInternal(ATTRIBUTENUM7);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeNum7.
     * @param value value to set the AttributeNum7
     */
    public void setAttributeNum7(Number value) {
        setAttributeInternal(ATTRIBUTENUM7, value);
    }

    /**
     * Gets the attribute value for AttributeNum8, using the alias name AttributeNum8.
     * @return the AttributeNum8
     */
    public Number getAttributeNum8() {
        return (Number)getAttributeInternal(ATTRIBUTENUM8);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeNum8.
     * @param value value to set the AttributeNum8
     */
    public void setAttributeNum8(Number value) {
        setAttributeInternal(ATTRIBUTENUM8, value);
    }

    /**
     * Gets the attribute value for AttributeNum9, using the alias name AttributeNum9.
     * @return the AttributeNum9
     */
    public Number getAttributeNum9() {
        return (Number)getAttributeInternal(ATTRIBUTENUM9);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeNum9.
     * @param value value to set the AttributeNum9
     */
    public void setAttributeNum9(Number value) {
        setAttributeInternal(ATTRIBUTENUM9, value);
    }

    /**
     * Gets the attribute value for AttributeNum10, using the alias name AttributeNum10.
     * @return the AttributeNum10
     */
    public Number getAttributeNum10() {
        return (Number)getAttributeInternal(ATTRIBUTENUM10);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeNum10.
     * @param value value to set the AttributeNum10
     */
    public void setAttributeNum10(Number value) {
        setAttributeInternal(ATTRIBUTENUM10, value);
    }

    /**
     * Gets the attribute value for AttributeDate1, using the alias name AttributeDate1.
     * @return the AttributeDate1
     */
    public Date getAttributeDate1() {
        return (Date)getAttributeInternal(ATTRIBUTEDATE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeDate1.
     * @param value value to set the AttributeDate1
     */
    public void setAttributeDate1(Date value) {
        setAttributeInternal(ATTRIBUTEDATE1, value);
    }

    /**
     * Gets the attribute value for AttributeDate2, using the alias name AttributeDate2.
     * @return the AttributeDate2
     */
    public Date getAttributeDate2() {
        return (Date)getAttributeInternal(ATTRIBUTEDATE2);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeDate2.
     * @param value value to set the AttributeDate2
     */
    public void setAttributeDate2(Date value) {
        setAttributeInternal(ATTRIBUTEDATE2, value);
    }

    /**
     * Gets the attribute value for AttributeDate3, using the alias name AttributeDate3.
     * @return the AttributeDate3
     */
    public Date getAttributeDate3() {
        return (Date)getAttributeInternal(ATTRIBUTEDATE3);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeDate3.
     * @param value value to set the AttributeDate3
     */
    public void setAttributeDate3(Date value) {
        setAttributeInternal(ATTRIBUTEDATE3, value);
    }

    /**
     * Gets the attribute value for AttributeDate4, using the alias name AttributeDate4.
     * @return the AttributeDate4
     */
    public Date getAttributeDate4() {
        return (Date)getAttributeInternal(ATTRIBUTEDATE4);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeDate4.
     * @param value value to set the AttributeDate4
     */
    public void setAttributeDate4(Date value) {
        setAttributeInternal(ATTRIBUTEDATE4, value);
    }

    /**
     * Gets the attribute value for AttributeDate5, using the alias name AttributeDate5.
     * @return the AttributeDate5
     */
    public Date getAttributeDate5() {
        return (Date)getAttributeInternal(ATTRIBUTEDATE5);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeDate5.
     * @param value value to set the AttributeDate5
     */
    public void setAttributeDate5(Date value) {
        setAttributeInternal(ATTRIBUTEDATE5, value);
    }

    /**
     * Gets the attribute value for CfsName, using the alias name CfsName.
     * @return the CfsName
     */
    public String getCfsName() {
        return (String)getAttributeInternal(CFSNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for CfsName.
     * @param value value to set the CfsName
     */
    public void setCfsName(String value) {
        setAttributeInternal(CFSNAME, value);
    }

    /**
     * Gets the attribute value for VehicleArrivalCfs, using the alias name VehicleArrivalCfs.
     * @return the VehicleArrivalCfs
     */
    public Date getVehicleArrivalCfs() {
        return (Date)getAttributeInternal(VEHICLEARRIVALCFS);
    }

    /**
     * Sets <code>value</code> as the attribute value for VehicleArrivalCfs.
     * @param value value to set the VehicleArrivalCfs
     */
    public void setVehicleArrivalCfs(Date value) {
        setAttributeInternal(VEHICLEARRIVALCFS, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity InlandTransportHeaderEOImpl.
     */
    public InlandTransportHeaderEOImpl getInlandTransportHeaderEO() {
        return (InlandTransportHeaderEOImpl)getAttributeInternal(INLANDTRANSPORTHEADEREO);
    }

    /**
     * Sets <code>value</code> as the associated entity InlandTransportHeaderEOImpl.
     */
    public void setInlandTransportHeaderEO(InlandTransportHeaderEOImpl value) {
        setAttributeInternal(INLANDTRANSPORTHEADEREO, value);
    }


    /**
     * @param inlandCommercialId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number inlandCommercialId) {
        return new Key(new Object[]{inlandCommercialId});
    }

    protected void create(AttributeList attributeList) {
            super.create(attributeList);
            /* Sequence Generation Code of Header by PwC */  
            oracle.jbo.server.SequenceImpl s = new oracle.jbo.server.SequenceImpl("IEDOC_EXP_INLAND_COMMERCIAL_S",getDBTransaction());          
            oracle.jbo.domain.Number sVal = s.getSequenceNumber();          
            setInlandCommercialId(sVal);
            /* End Sequence Generation Code of Header by PwC */
        }
    


}
