package mnj.ont.model.entities;

import java.sql.SQLException;

import java.util.Map;

import oracle.adf.share.ADFContext;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jan 09 15:30:55 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InlandTransportHeaderEOImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        InlandTransHeaderId {
            public Object get(InlandTransportHeaderEOImpl obj) {
                return obj.getInlandTransHeaderId();
            }

            public void put(InlandTransportHeaderEOImpl obj, Object value) {
                obj.setInlandTransHeaderId((Number)value);
            }
        }
        ,
        TransportationAgencyName {
            public Object get(InlandTransportHeaderEOImpl obj) {
                return obj.getTransportationAgencyName();
            }

            public void put(InlandTransportHeaderEOImpl obj, Object value) {
                obj.setTransportationAgencyName((String)value);
            }
        }
        ,
        TransportationCompanyName {
            public Object get(InlandTransportHeaderEOImpl obj) {
                return obj.getTransportationCompanyName();
            }

            public void put(InlandTransportHeaderEOImpl obj, Object value) {
                obj.setTransportationCompanyName((String)value);
            }
        }
        ,
        VehicleNumber {
            public Object get(InlandTransportHeaderEOImpl obj) {
                return obj.getVehicleNumber();
            }

            public void put(InlandTransportHeaderEOImpl obj, Object value) {
                obj.setVehicleNumber((String)value);
            }
        }
        ,
        VehicleArrivalDate {
            public Object get(InlandTransportHeaderEOImpl obj) {
                return obj.getVehicleArrivalDate();
            }

            public void put(InlandTransportHeaderEOImpl obj, Object value) {
                obj.setVehicleArrivalDate((Date)value);
            }
        }
        ,
        VehicleDepartureDate {
            public Object get(InlandTransportHeaderEOImpl obj) {
                return obj.getVehicleDepartureDate();
            }

            public void put(InlandTransportHeaderEOImpl obj, Object value) {
                obj.setVehicleDepartureDate((Date)value);
            }
        }
        ,
        ExFactoryDate {
            public Object get(InlandTransportHeaderEOImpl obj) {
                return obj.getExFactoryDate();
            }

            public void put(InlandTransportHeaderEOImpl obj, Object value) {
                obj.setExFactoryDate((Date)value);
            }
        }
        ,
        DriverName {
            public Object get(InlandTransportHeaderEOImpl obj) {
                return obj.getDriverName();
            }

            public void put(InlandTransportHeaderEOImpl obj, Object value) {
                obj.setDriverName((String)value);
            }
        }
        ,
        DriverMobileNumber {
            public Object get(InlandTransportHeaderEOImpl obj) {
                return obj.getDriverMobileNumber();
            }

            public void put(InlandTransportHeaderEOImpl obj, Object value) {
                obj.setDriverMobileNumber((String)value);
            }
        }
        ,
        DriverLicenseNumber {
            public Object get(InlandTransportHeaderEOImpl obj) {
                return obj.getDriverLicenseNumber();
            }

            public void put(InlandTransportHeaderEOImpl obj, Object value) {
                obj.setDriverLicenseNumber((String)value);
            }
        }
        ,
        EscortName {
            public Object get(InlandTransportHeaderEOImpl obj) {
                return obj.getEscortName();
            }

            public void put(InlandTransportHeaderEOImpl obj, Object value) {
                obj.setEscortName((String)value);
            }
        }
        ,
        EscortMobileNumber {
            public Object get(InlandTransportHeaderEOImpl obj) {
                return obj.getEscortMobileNumber();
            }

            public void put(InlandTransportHeaderEOImpl obj, Object value) {
                obj.setEscortMobileNumber((String)value);
            }
        }
        ,
        StatusMode {
            public Object get(InlandTransportHeaderEOImpl obj) {
                return obj.getStatusMode();
            }

            public void put(InlandTransportHeaderEOImpl obj, Object value) {
                obj.setStatusMode((String)value);
            }
        }
        ,
        OrgId {
            public Object get(InlandTransportHeaderEOImpl obj) {
                return obj.getOrgId();
            }

            public void put(InlandTransportHeaderEOImpl obj, Object value) {
                obj.setOrgId((Number)value);
            }
        }
        ,
        LockNumber {
            public Object get(InlandTransportHeaderEOImpl obj) {
                return obj.getLockNumber();
            }

            public void put(InlandTransportHeaderEOImpl obj, Object value) {
                obj.setLockNumber((String)value);
            }
        }
        ,
        Remarks {
            public Object get(InlandTransportHeaderEOImpl obj) {
                return obj.getRemarks();
            }

            public void put(InlandTransportHeaderEOImpl obj, Object value) {
                obj.setRemarks((String)value);
            }
        }
        ,
        LastUpdateLogin {
            public Object get(InlandTransportHeaderEOImpl obj) {
                return obj.getLastUpdateLogin();
            }

            public void put(InlandTransportHeaderEOImpl obj, Object value) {
                obj.setLastUpdateLogin((Number)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(InlandTransportHeaderEOImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(InlandTransportHeaderEOImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(InlandTransportHeaderEOImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(InlandTransportHeaderEOImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(InlandTransportHeaderEOImpl obj) {
                return obj.getCreationDate();
            }

            public void put(InlandTransportHeaderEOImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(InlandTransportHeaderEOImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(InlandTransportHeaderEOImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        Attribute1 {
            public Object get(InlandTransportHeaderEOImpl obj) {
                return obj.getAttribute1();
            }

            public void put(InlandTransportHeaderEOImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(InlandTransportHeaderEOImpl obj) {
                return obj.getAttribute2();
            }

            public void put(InlandTransportHeaderEOImpl obj, Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(InlandTransportHeaderEOImpl obj) {
                return obj.getAttribute3();
            }

            public void put(InlandTransportHeaderEOImpl obj, Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(InlandTransportHeaderEOImpl obj) {
                return obj.getAttribute4();
            }

            public void put(InlandTransportHeaderEOImpl obj, Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(InlandTransportHeaderEOImpl obj) {
                return obj.getAttribute5();
            }

            public void put(InlandTransportHeaderEOImpl obj, Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(InlandTransportHeaderEOImpl obj) {
                return obj.getAttribute6();
            }

            public void put(InlandTransportHeaderEOImpl obj, Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(InlandTransportHeaderEOImpl obj) {
                return obj.getAttribute7();
            }

            public void put(InlandTransportHeaderEOImpl obj, Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(InlandTransportHeaderEOImpl obj) {
                return obj.getAttribute8();
            }

            public void put(InlandTransportHeaderEOImpl obj, Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(InlandTransportHeaderEOImpl obj) {
                return obj.getAttribute9();
            }

            public void put(InlandTransportHeaderEOImpl obj, Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        Attribute10 {
            public Object get(InlandTransportHeaderEOImpl obj) {
                return obj.getAttribute10();
            }

            public void put(InlandTransportHeaderEOImpl obj, Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        Attribute11 {
            public Object get(InlandTransportHeaderEOImpl obj) {
                return obj.getAttribute11();
            }

            public void put(InlandTransportHeaderEOImpl obj, Object value) {
                obj.setAttribute11((String)value);
            }
        }
        ,
        Attribute12 {
            public Object get(InlandTransportHeaderEOImpl obj) {
                return obj.getAttribute12();
            }

            public void put(InlandTransportHeaderEOImpl obj, Object value) {
                obj.setAttribute12((String)value);
            }
        }
        ,
        Attribute13 {
            public Object get(InlandTransportHeaderEOImpl obj) {
                return obj.getAttribute13();
            }

            public void put(InlandTransportHeaderEOImpl obj, Object value) {
                obj.setAttribute13((String)value);
            }
        }
        ,
        Attribute14 {
            public Object get(InlandTransportHeaderEOImpl obj) {
                return obj.getAttribute14();
            }

            public void put(InlandTransportHeaderEOImpl obj, Object value) {
                obj.setAttribute14((String)value);
            }
        }
        ,
        Attribute15 {
            public Object get(InlandTransportHeaderEOImpl obj) {
                return obj.getAttribute15();
            }

            public void put(InlandTransportHeaderEOImpl obj, Object value) {
                obj.setAttribute15((String)value);
            }
        }
        ,
        Attribute16 {
            public Object get(InlandTransportHeaderEOImpl obj) {
                return obj.getAttribute16();
            }

            public void put(InlandTransportHeaderEOImpl obj, Object value) {
                obj.setAttribute16((String)value);
            }
        }
        ,
        Attribute17 {
            public Object get(InlandTransportHeaderEOImpl obj) {
                return obj.getAttribute17();
            }

            public void put(InlandTransportHeaderEOImpl obj, Object value) {
                obj.setAttribute17((String)value);
            }
        }
        ,
        Attribute18 {
            public Object get(InlandTransportHeaderEOImpl obj) {
                return obj.getAttribute18();
            }

            public void put(InlandTransportHeaderEOImpl obj, Object value) {
                obj.setAttribute18((String)value);
            }
        }
        ,
        Attribute19 {
            public Object get(InlandTransportHeaderEOImpl obj) {
                return obj.getAttribute19();
            }

            public void put(InlandTransportHeaderEOImpl obj, Object value) {
                obj.setAttribute19((String)value);
            }
        }
        ,
        Attribute20 {
            public Object get(InlandTransportHeaderEOImpl obj) {
                return obj.getAttribute20();
            }

            public void put(InlandTransportHeaderEOImpl obj, Object value) {
                obj.setAttribute20((String)value);
            }
        }
        ,
        AttributeNum1 {
            public Object get(InlandTransportHeaderEOImpl obj) {
                return obj.getAttributeNum1();
            }

            public void put(InlandTransportHeaderEOImpl obj, Object value) {
                obj.setAttributeNum1((Number)value);
            }
        }
        ,
        AttributeNum2 {
            public Object get(InlandTransportHeaderEOImpl obj) {
                return obj.getAttributeNum2();
            }

            public void put(InlandTransportHeaderEOImpl obj, Object value) {
                obj.setAttributeNum2((Number)value);
            }
        }
        ,
        AttributeNum3 {
            public Object get(InlandTransportHeaderEOImpl obj) {
                return obj.getAttributeNum3();
            }

            public void put(InlandTransportHeaderEOImpl obj, Object value) {
                obj.setAttributeNum3((Number)value);
            }
        }
        ,
        AttributeNum4 {
            public Object get(InlandTransportHeaderEOImpl obj) {
                return obj.getAttributeNum4();
            }

            public void put(InlandTransportHeaderEOImpl obj, Object value) {
                obj.setAttributeNum4((Number)value);
            }
        }
        ,
        AttributeNum5 {
            public Object get(InlandTransportHeaderEOImpl obj) {
                return obj.getAttributeNum5();
            }

            public void put(InlandTransportHeaderEOImpl obj, Object value) {
                obj.setAttributeNum5((Number)value);
            }
        }
        ,
        AttributeNum6 {
            public Object get(InlandTransportHeaderEOImpl obj) {
                return obj.getAttributeNum6();
            }

            public void put(InlandTransportHeaderEOImpl obj, Object value) {
                obj.setAttributeNum6((Number)value);
            }
        }
        ,
        AttributeNum7 {
            public Object get(InlandTransportHeaderEOImpl obj) {
                return obj.getAttributeNum7();
            }

            public void put(InlandTransportHeaderEOImpl obj, Object value) {
                obj.setAttributeNum7((Number)value);
            }
        }
        ,
        AttributeNum8 {
            public Object get(InlandTransportHeaderEOImpl obj) {
                return obj.getAttributeNum8();
            }

            public void put(InlandTransportHeaderEOImpl obj, Object value) {
                obj.setAttributeNum8((Number)value);
            }
        }
        ,
        AttributeNum9 {
            public Object get(InlandTransportHeaderEOImpl obj) {
                return obj.getAttributeNum9();
            }

            public void put(InlandTransportHeaderEOImpl obj, Object value) {
                obj.setAttributeNum9((Number)value);
            }
        }
        ,
        AttributeNum10 {
            public Object get(InlandTransportHeaderEOImpl obj) {
                return obj.getAttributeNum10();
            }

            public void put(InlandTransportHeaderEOImpl obj, Object value) {
                obj.setAttributeNum10((String)value);
            }
        }
        ,
        AttributeDate1 {
            public Object get(InlandTransportHeaderEOImpl obj) {
                return obj.getAttributeDate1();
            }

            public void put(InlandTransportHeaderEOImpl obj, Object value) {
                obj.setAttributeDate1((Date)value);
            }
        }
        ,
        AttributeDate2 {
            public Object get(InlandTransportHeaderEOImpl obj) {
                return obj.getAttributeDate2();
            }

            public void put(InlandTransportHeaderEOImpl obj, Object value) {
                obj.setAttributeDate2((Date)value);
            }
        }
        ,
        AttributeDate3 {
            public Object get(InlandTransportHeaderEOImpl obj) {
                return obj.getAttributeDate3();
            }

            public void put(InlandTransportHeaderEOImpl obj, Object value) {
                obj.setAttributeDate3((Date)value);
            }
        }
        ,
        AttributeDate4 {
            public Object get(InlandTransportHeaderEOImpl obj) {
                return obj.getAttributeDate4();
            }

            public void put(InlandTransportHeaderEOImpl obj, Object value) {
                obj.setAttributeDate4((Date)value);
            }
        }
        ,
        AttributeDate5 {
            public Object get(InlandTransportHeaderEOImpl obj) {
                return obj.getAttributeDate5();
            }

            public void put(InlandTransportHeaderEOImpl obj, Object value) {
                obj.setAttributeDate5((Date)value);
            }
        }
        ,
        TotalCbm {
            public Object get(InlandTransportHeaderEOImpl obj) {
                return obj.getTotalCbm();
            }

            public void put(InlandTransportHeaderEOImpl obj, Object value) {
                obj.setTotalCbm((Number)value);
            }
        }
        ,
        EscortId {
            public Object get(InlandTransportHeaderEOImpl obj) {
                return obj.getEscortId();
            }

            public void put(InlandTransportHeaderEOImpl obj, Object value) {
                obj.setEscortId((Number)value);
            }
        }
        ,
        RcvFlag {
            public Object get(InlandTransportHeaderEOImpl obj) {
                return obj.getRcvFlag();
            }

            public void put(InlandTransportHeaderEOImpl obj, Object value) {
                obj.setRcvFlag((String)value);
            }
        }
        ,
        DepartureTime {
            public Object get(InlandTransportHeaderEOImpl obj) {
                return obj.getDepartureTime();
            }

            public void put(InlandTransportHeaderEOImpl obj, Object value) {
                obj.setDepartureTime((Date)value);
            }
        }
        ,
        EmptyCarton {
            public Object get(InlandTransportHeaderEOImpl obj) {
                return obj.getEmptyCarton();
            }

            public void put(InlandTransportHeaderEOImpl obj, Object value) {
                obj.setEmptyCarton((String)value);
            }
        }
        ,
        GumTap {
            public Object get(InlandTransportHeaderEOImpl obj) {
                return obj.getGumTap();
            }

            public void put(InlandTransportHeaderEOImpl obj, Object value) {
                obj.setGumTap((String)value);
            }
        }
        ,
        InlandTransportLinesEO {
            public Object get(InlandTransportHeaderEOImpl obj) {
                return obj.getInlandTransportLinesEO();
            }

            public void put(InlandTransportHeaderEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CommercalTabEo {
            public Object get(InlandTransportHeaderEOImpl obj) {
                return obj.getCommercalTabEo();
            }

            public void put(InlandTransportHeaderEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(InlandTransportHeaderEOImpl object);

        public abstract void put(InlandTransportHeaderEOImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int INLANDTRANSHEADERID = AttributesEnum.InlandTransHeaderId.index();
    public static final int TRANSPORTATIONAGENCYNAME = AttributesEnum.TransportationAgencyName.index();
    public static final int TRANSPORTATIONCOMPANYNAME = AttributesEnum.TransportationCompanyName.index();
    public static final int VEHICLENUMBER = AttributesEnum.VehicleNumber.index();
    public static final int VEHICLEARRIVALDATE = AttributesEnum.VehicleArrivalDate.index();
    public static final int VEHICLEDEPARTUREDATE = AttributesEnum.VehicleDepartureDate.index();
    public static final int EXFACTORYDATE = AttributesEnum.ExFactoryDate.index();
    public static final int DRIVERNAME = AttributesEnum.DriverName.index();
    public static final int DRIVERMOBILENUMBER = AttributesEnum.DriverMobileNumber.index();
    public static final int DRIVERLICENSENUMBER = AttributesEnum.DriverLicenseNumber.index();
    public static final int ESCORTNAME = AttributesEnum.EscortName.index();
    public static final int ESCORTMOBILENUMBER = AttributesEnum.EscortMobileNumber.index();
    public static final int STATUSMODE = AttributesEnum.StatusMode.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int LOCKNUMBER = AttributesEnum.LockNumber.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int ATTRIBUTE11 = AttributesEnum.Attribute11.index();
    public static final int ATTRIBUTE12 = AttributesEnum.Attribute12.index();
    public static final int ATTRIBUTE13 = AttributesEnum.Attribute13.index();
    public static final int ATTRIBUTE14 = AttributesEnum.Attribute14.index();
    public static final int ATTRIBUTE15 = AttributesEnum.Attribute15.index();
    public static final int ATTRIBUTE16 = AttributesEnum.Attribute16.index();
    public static final int ATTRIBUTE17 = AttributesEnum.Attribute17.index();
    public static final int ATTRIBUTE18 = AttributesEnum.Attribute18.index();
    public static final int ATTRIBUTE19 = AttributesEnum.Attribute19.index();
    public static final int ATTRIBUTE20 = AttributesEnum.Attribute20.index();
    public static final int ATTRIBUTENUM1 = AttributesEnum.AttributeNum1.index();
    public static final int ATTRIBUTENUM2 = AttributesEnum.AttributeNum2.index();
    public static final int ATTRIBUTENUM3 = AttributesEnum.AttributeNum3.index();
    public static final int ATTRIBUTENUM4 = AttributesEnum.AttributeNum4.index();
    public static final int ATTRIBUTENUM5 = AttributesEnum.AttributeNum5.index();
    public static final int ATTRIBUTENUM6 = AttributesEnum.AttributeNum6.index();
    public static final int ATTRIBUTENUM7 = AttributesEnum.AttributeNum7.index();
    public static final int ATTRIBUTENUM8 = AttributesEnum.AttributeNum8.index();
    public static final int ATTRIBUTENUM9 = AttributesEnum.AttributeNum9.index();
    public static final int ATTRIBUTENUM10 = AttributesEnum.AttributeNum10.index();
    public static final int ATTRIBUTEDATE1 = AttributesEnum.AttributeDate1.index();
    public static final int ATTRIBUTEDATE2 = AttributesEnum.AttributeDate2.index();
    public static final int ATTRIBUTEDATE3 = AttributesEnum.AttributeDate3.index();
    public static final int ATTRIBUTEDATE4 = AttributesEnum.AttributeDate4.index();
    public static final int ATTRIBUTEDATE5 = AttributesEnum.AttributeDate5.index();
    public static final int TOTALCBM = AttributesEnum.TotalCbm.index();
    public static final int ESCORTID = AttributesEnum.EscortId.index();
    public static final int RCVFLAG = AttributesEnum.RcvFlag.index();
    public static final int DEPARTURETIME = AttributesEnum.DepartureTime.index();
    public static final int EMPTYCARTON = AttributesEnum.EmptyCarton.index();
    public static final int GUMTAP = AttributesEnum.GumTap.index();
    public static final int INLANDTRANSPORTLINESEO = AttributesEnum.InlandTransportLinesEO.index();
    public static final int COMMERCALTABEO = AttributesEnum.CommercalTabEo.index();

    /**
     * This is the default constructor (do not remove).
     */
    public InlandTransportHeaderEOImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("mnj.ont.model.entities.InlandTransportHeaderEO");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for InlandTransHeaderId, using the alias name InlandTransHeaderId.
     * @return the InlandTransHeaderId
     */
    public Number getInlandTransHeaderId() {
        return (Number)getAttributeInternal(INLANDTRANSHEADERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for InlandTransHeaderId.
     * @param value value to set the InlandTransHeaderId
     */
    public void setInlandTransHeaderId(Number value) {
        setAttributeInternal(INLANDTRANSHEADERID, value);
    }

    /**
     * Gets the attribute value for TransportationAgencyName, using the alias name TransportationAgencyName.
     * @return the TransportationAgencyName
     */
    public String getTransportationAgencyName() {
        return (String)getAttributeInternal(TRANSPORTATIONAGENCYNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for TransportationAgencyName.
     * @param value value to set the TransportationAgencyName
     */
    public void setTransportationAgencyName(String value) {
        setAttributeInternal(TRANSPORTATIONAGENCYNAME, value);
    }

    /**
     * Gets the attribute value for TransportationCompanyName, using the alias name TransportationCompanyName.
     * @return the TransportationCompanyName
     */
    public String getTransportationCompanyName() {
        return (String)getAttributeInternal(TRANSPORTATIONCOMPANYNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for TransportationCompanyName.
     * @param value value to set the TransportationCompanyName
     */
    public void setTransportationCompanyName(String value) {
        setAttributeInternal(TRANSPORTATIONCOMPANYNAME, value);
    }

    /**
     * Gets the attribute value for VehicleNumber, using the alias name VehicleNumber.
     * @return the VehicleNumber
     */
    public String getVehicleNumber() {
        return (String)getAttributeInternal(VEHICLENUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for VehicleNumber.
     * @param value value to set the VehicleNumber
     */
    public void setVehicleNumber(String value) {
        setAttributeInternal(VEHICLENUMBER, value);
    }

    /**
     * Gets the attribute value for VehicleArrivalDate, using the alias name VehicleArrivalDate.
     * @return the VehicleArrivalDate
     */
    public Date getVehicleArrivalDate() {
        return (Date)getAttributeInternal(VEHICLEARRIVALDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for VehicleArrivalDate.
     * @param value value to set the VehicleArrivalDate
     */
    public void setVehicleArrivalDate(Date value) {
        setAttributeInternal(VEHICLEARRIVALDATE, value);
    }

    /**
     * Gets the attribute value for VehicleDepartureDate, using the alias name VehicleDepartureDate.
     * @return the VehicleDepartureDate
     */
    public Date getVehicleDepartureDate() {
        return (Date)getAttributeInternal(VEHICLEDEPARTUREDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for VehicleDepartureDate.
     * @param value value to set the VehicleDepartureDate
     */
    public void setVehicleDepartureDate(Date value) {
        setAttributeInternal(VEHICLEDEPARTUREDATE, value);
    }

    /**
     * Gets the attribute value for ExFactoryDate, using the alias name ExFactoryDate.
     * @return the ExFactoryDate
     */
    public Date getExFactoryDate() {
        return (Date)getAttributeInternal(EXFACTORYDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExFactoryDate.
     * @param value value to set the ExFactoryDate
     */
    public void setExFactoryDate(Date value) {
        setAttributeInternal(EXFACTORYDATE, value);
    }

    /**
     * Gets the attribute value for DriverName, using the alias name DriverName.
     * @return the DriverName
     */
    public String getDriverName() {
        return (String)getAttributeInternal(DRIVERNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for DriverName.
     * @param value value to set the DriverName
     */
    public void setDriverName(String value) {
        setAttributeInternal(DRIVERNAME, value);
    }

    /**
     * Gets the attribute value for DriverMobileNumber, using the alias name DriverMobileNumber.
     * @return the DriverMobileNumber
     */
    public String getDriverMobileNumber() {
        return (String)getAttributeInternal(DRIVERMOBILENUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for DriverMobileNumber.
     * @param value value to set the DriverMobileNumber
     */
    public void setDriverMobileNumber(String value) {
        setAttributeInternal(DRIVERMOBILENUMBER, value);
    }

    /**
     * Gets the attribute value for DriverLicenseNumber, using the alias name DriverLicenseNumber.
     * @return the DriverLicenseNumber
     */
    public String getDriverLicenseNumber() {
        return (String)getAttributeInternal(DRIVERLICENSENUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for DriverLicenseNumber.
     * @param value value to set the DriverLicenseNumber
     */
    public void setDriverLicenseNumber(String value) {
        setAttributeInternal(DRIVERLICENSENUMBER, value);
    }

    /**
     * Gets the attribute value for EscortName, using the alias name EscortName.
     * @return the EscortName
     */
    public String getEscortName() {
        return (String)getAttributeInternal(ESCORTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for EscortName.
     * @param value value to set the EscortName
     */
    public void setEscortName(String value) {
        setAttributeInternal(ESCORTNAME, value);
    }

    /**
     * Gets the attribute value for EscortMobileNumber, using the alias name EscortMobileNumber.
     * @return the EscortMobileNumber
     */
    public String getEscortMobileNumber() {
        return (String)getAttributeInternal(ESCORTMOBILENUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for EscortMobileNumber.
     * @param value value to set the EscortMobileNumber
     */
    public void setEscortMobileNumber(String value) {
        setAttributeInternal(ESCORTMOBILENUMBER, value);
    }

    /**
     * Gets the attribute value for StatusMode, using the alias name StatusMode.
     * @return the StatusMode
     */
    public String getStatusMode() {
        return (String)getAttributeInternal(STATUSMODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for StatusMode.
     * @param value value to set the StatusMode
     */
    public void setStatusMode(String value) {
        setAttributeInternal(STATUSMODE, value);
    }

    /**
     * Gets the attribute value for OrgId, using the alias name OrgId.
     * @return the OrgId
     */
    public Number getOrgId() {
        return (Number)getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrgId.
     * @param value value to set the OrgId
     */
    public void setOrgId(Number value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for LockNumber, using the alias name LockNumber.
     * @return the LockNumber
     */
    public String getLockNumber() {
        return (String)getAttributeInternal(LOCKNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for LockNumber.
     * @param value value to set the LockNumber
     */
    public void setLockNumber(String value) {
        setAttributeInternal(LOCKNUMBER, value);
    }

    /**
     * Gets the attribute value for Remarks, using the alias name Remarks.
     * @return the Remarks
     */
    public String getRemarks() {
        return (String)getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Remarks.
     * @param value value to set the Remarks
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin.
     * @return the LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number)getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateLogin.
     * @param value value to set the LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateDate.
     * @param value value to set the LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for Attribute1, using the alias name Attribute1.
     * @return the Attribute1
     */
    public String getAttribute1() {
        return (String)getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute1.
     * @param value value to set the Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for Attribute2, using the alias name Attribute2.
     * @return the Attribute2
     */
    public String getAttribute2() {
        return (String)getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute2.
     * @param value value to set the Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for Attribute3, using the alias name Attribute3.
     * @return the Attribute3
     */
    public String getAttribute3() {
        return (String)getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute3.
     * @param value value to set the Attribute3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for Attribute4, using the alias name Attribute4.
     * @return the Attribute4
     */
    public String getAttribute4() {
        return (String)getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute4.
     * @param value value to set the Attribute4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for Attribute5, using the alias name Attribute5.
     * @return the Attribute5
     */
    public String getAttribute5() {
        return (String)getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute5.
     * @param value value to set the Attribute5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for Attribute6, using the alias name Attribute6.
     * @return the Attribute6
     */
    public String getAttribute6() {
        return (String)getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute6.
     * @param value value to set the Attribute6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for Attribute7, using the alias name Attribute7.
     * @return the Attribute7
     */
    public String getAttribute7() {
        return (String)getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute7.
     * @param value value to set the Attribute7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for Attribute8, using the alias name Attribute8.
     * @return the Attribute8
     */
    public String getAttribute8() {
        return (String)getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute8.
     * @param value value to set the Attribute8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for Attribute9, using the alias name Attribute9.
     * @return the Attribute9
     */
    public String getAttribute9() {
        return (String)getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute9.
     * @param value value to set the Attribute9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for Attribute10, using the alias name Attribute10.
     * @return the Attribute10
     */
    public String getAttribute10() {
        return (String)getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute10.
     * @param value value to set the Attribute10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for Attribute11, using the alias name Attribute11.
     * @return the Attribute11
     */
    public String getAttribute11() {
        return (String)getAttributeInternal(ATTRIBUTE11);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute11.
     * @param value value to set the Attribute11
     */
    public void setAttribute11(String value) {
        setAttributeInternal(ATTRIBUTE11, value);
    }

    /**
     * Gets the attribute value for Attribute12, using the alias name Attribute12.
     * @return the Attribute12
     */
    public String getAttribute12() {
        return (String)getAttributeInternal(ATTRIBUTE12);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute12.
     * @param value value to set the Attribute12
     */
    public void setAttribute12(String value) {
        setAttributeInternal(ATTRIBUTE12, value);
    }

    /**
     * Gets the attribute value for Attribute13, using the alias name Attribute13.
     * @return the Attribute13
     */
    public String getAttribute13() {
        return (String)getAttributeInternal(ATTRIBUTE13);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute13.
     * @param value value to set the Attribute13
     */
    public void setAttribute13(String value) {
        setAttributeInternal(ATTRIBUTE13, value);
    }

    /**
     * Gets the attribute value for Attribute14, using the alias name Attribute14.
     * @return the Attribute14
     */
    public String getAttribute14() {
        return (String)getAttributeInternal(ATTRIBUTE14);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute14.
     * @param value value to set the Attribute14
     */
    public void setAttribute14(String value) {
        setAttributeInternal(ATTRIBUTE14, value);
    }

    /**
     * Gets the attribute value for Attribute15, using the alias name Attribute15.
     * @return the Attribute15
     */
    public String getAttribute15() {
        return (String)getAttributeInternal(ATTRIBUTE15);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute15.
     * @param value value to set the Attribute15
     */
    public void setAttribute15(String value) {
        setAttributeInternal(ATTRIBUTE15, value);
    }

    /**
     * Gets the attribute value for Attribute16, using the alias name Attribute16.
     * @return the Attribute16
     */
    public String getAttribute16() {
        return (String)getAttributeInternal(ATTRIBUTE16);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute16.
     * @param value value to set the Attribute16
     */
    public void setAttribute16(String value) {
        setAttributeInternal(ATTRIBUTE16, value);
    }

    /**
     * Gets the attribute value for Attribute17, using the alias name Attribute17.
     * @return the Attribute17
     */
    public String getAttribute17() {
        return (String)getAttributeInternal(ATTRIBUTE17);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute17.
     * @param value value to set the Attribute17
     */
    public void setAttribute17(String value) {
        setAttributeInternal(ATTRIBUTE17, value);
    }

    /**
     * Gets the attribute value for Attribute18, using the alias name Attribute18.
     * @return the Attribute18
     */
    public String getAttribute18() {
        return (String)getAttributeInternal(ATTRIBUTE18);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute18.
     * @param value value to set the Attribute18
     */
    public void setAttribute18(String value) {
        setAttributeInternal(ATTRIBUTE18, value);
    }

    /**
     * Gets the attribute value for Attribute19, using the alias name Attribute19.
     * @return the Attribute19
     */
    public String getAttribute19() {
        return (String)getAttributeInternal(ATTRIBUTE19);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute19.
     * @param value value to set the Attribute19
     */
    public void setAttribute19(String value) {
        setAttributeInternal(ATTRIBUTE19, value);
    }

    /**
     * Gets the attribute value for Attribute20, using the alias name Attribute20.
     * @return the Attribute20
     */
    public String getAttribute20() {
        return (String)getAttributeInternal(ATTRIBUTE20);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute20.
     * @param value value to set the Attribute20
     */
    public void setAttribute20(String value) {
        setAttributeInternal(ATTRIBUTE20, value);
    }

    /**
     * Gets the attribute value for AttributeNum1, using the alias name AttributeNum1.
     * @return the AttributeNum1
     */
    public Number getAttributeNum1() {
        return (Number)getAttributeInternal(ATTRIBUTENUM1);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeNum1.
     * @param value value to set the AttributeNum1
     */
    public void setAttributeNum1(Number value) {
        setAttributeInternal(ATTRIBUTENUM1, value);
    }

    /**
     * Gets the attribute value for AttributeNum2, using the alias name AttributeNum2.
     * @return the AttributeNum2
     */
    public Number getAttributeNum2() {
        return (Number)getAttributeInternal(ATTRIBUTENUM2);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeNum2.
     * @param value value to set the AttributeNum2
     */
    public void setAttributeNum2(Number value) {
        setAttributeInternal(ATTRIBUTENUM2, value);
    }

    /**
     * Gets the attribute value for AttributeNum3, using the alias name AttributeNum3.
     * @return the AttributeNum3
     */
    public Number getAttributeNum3() {
        return (Number)getAttributeInternal(ATTRIBUTENUM3);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeNum3.
     * @param value value to set the AttributeNum3
     */
    public void setAttributeNum3(Number value) {
        setAttributeInternal(ATTRIBUTENUM3, value);
    }

    /**
     * Gets the attribute value for AttributeNum4, using the alias name AttributeNum4.
     * @return the AttributeNum4
     */
    public Number getAttributeNum4() {
        return (Number)getAttributeInternal(ATTRIBUTENUM4);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeNum4.
     * @param value value to set the AttributeNum4
     */
    public void setAttributeNum4(Number value) {
        setAttributeInternal(ATTRIBUTENUM4, value);
    }

    /**
     * Gets the attribute value for AttributeNum5, using the alias name AttributeNum5.
     * @return the AttributeNum5
     */
    public Number getAttributeNum5() {
        return (Number)getAttributeInternal(ATTRIBUTENUM5);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeNum5.
     * @param value value to set the AttributeNum5
     */
    public void setAttributeNum5(Number value) {
        setAttributeInternal(ATTRIBUTENUM5, value);
    }

    /**
     * Gets the attribute value for AttributeNum6, using the alias name AttributeNum6.
     * @return the AttributeNum6
     */
    public Number getAttributeNum6() {
        return (Number)getAttributeInternal(ATTRIBUTENUM6);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeNum6.
     * @param value value to set the AttributeNum6
     */
    public void setAttributeNum6(Number value) {
        setAttributeInternal(ATTRIBUTENUM6, value);
    }

    /**
     * Gets the attribute value for AttributeNum7, using the alias name AttributeNum7.
     * @return the AttributeNum7
     */
    public Number getAttributeNum7() {
        return (Number)getAttributeInternal(ATTRIBUTENUM7);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeNum7.
     * @param value value to set the AttributeNum7
     */
    public void setAttributeNum7(Number value) {
        setAttributeInternal(ATTRIBUTENUM7, value);
    }

    /**
     * Gets the attribute value for AttributeNum8, using the alias name AttributeNum8.
     * @return the AttributeNum8
     */
    public Number getAttributeNum8() {
        return (Number)getAttributeInternal(ATTRIBUTENUM8);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeNum8.
     * @param value value to set the AttributeNum8
     */
    public void setAttributeNum8(Number value) {
        setAttributeInternal(ATTRIBUTENUM8, value);
    }

    /**
     * Gets the attribute value for AttributeNum9, using the alias name AttributeNum9.
     * @return the AttributeNum9
     */
    public Number getAttributeNum9() {
        return (Number)getAttributeInternal(ATTRIBUTENUM9);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeNum9.
     * @param value value to set the AttributeNum9
     */
    public void setAttributeNum9(Number value) {
        setAttributeInternal(ATTRIBUTENUM9, value);
    }

    /**
     * Gets the attribute value for AttributeNum10, using the alias name AttributeNum10.
     * @return the AttributeNum10
     */
    public String getAttributeNum10() {
        return (String)getAttributeInternal(ATTRIBUTENUM10);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeNum10.
     * @param value value to set the AttributeNum10
     */
    public void setAttributeNum10(String value) {
        setAttributeInternal(ATTRIBUTENUM10, value);
    }

    /**
     * Gets the attribute value for AttributeDate1, using the alias name AttributeDate1.
     * @return the AttributeDate1
     */
    public Date getAttributeDate1() {
        return (Date)getAttributeInternal(ATTRIBUTEDATE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeDate1.
     * @param value value to set the AttributeDate1
     */
    public void setAttributeDate1(Date value) {
        setAttributeInternal(ATTRIBUTEDATE1, value);
    }

    /**
     * Gets the attribute value for AttributeDate2, using the alias name AttributeDate2.
     * @return the AttributeDate2
     */
    public Date getAttributeDate2() {
        return (Date)getAttributeInternal(ATTRIBUTEDATE2);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeDate2.
     * @param value value to set the AttributeDate2
     */
    public void setAttributeDate2(Date value) {
        setAttributeInternal(ATTRIBUTEDATE2, value);
    }

    /**
     * Gets the attribute value for AttributeDate3, using the alias name AttributeDate3.
     * @return the AttributeDate3
     */
    public Date getAttributeDate3() {
        return (Date)getAttributeInternal(ATTRIBUTEDATE3);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeDate3.
     * @param value value to set the AttributeDate3
     */
    public void setAttributeDate3(Date value) {
        setAttributeInternal(ATTRIBUTEDATE3, value);
    }

    /**
     * Gets the attribute value for AttributeDate4, using the alias name AttributeDate4.
     * @return the AttributeDate4
     */
    public Date getAttributeDate4() {
        return (Date)getAttributeInternal(ATTRIBUTEDATE4);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeDate4.
     * @param value value to set the AttributeDate4
     */
    public void setAttributeDate4(Date value) {
        setAttributeInternal(ATTRIBUTEDATE4, value);
    }

    /**
     * Gets the attribute value for AttributeDate5, using the alias name AttributeDate5.
     * @return the AttributeDate5
     */
    public Date getAttributeDate5() {
        return (Date)getAttributeInternal(ATTRIBUTEDATE5);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeDate5.
     * @param value value to set the AttributeDate5
     */
    public void setAttributeDate5(Date value) {
        setAttributeInternal(ATTRIBUTEDATE5, value);
    }

    /**
     * Gets the attribute value for TotalCbm, using the alias name TotalCbm.
     * @return the TotalCbm
     */
    public Number getTotalCbm() {
        return (Number)getAttributeInternal(TOTALCBM);
    }

    /**
     * Sets <code>value</code> as the attribute value for TotalCbm.
     * @param value value to set the TotalCbm
     */
    public void setTotalCbm(Number value) {
        setAttributeInternal(TOTALCBM, value);
    }

    /**
     * Gets the attribute value for EscortId, using the alias name EscortId.
     * @return the EscortId
     */
    public Number getEscortId() {
        return (Number)getAttributeInternal(ESCORTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for EscortId.
     * @param value value to set the EscortId
     */
    public void setEscortId(Number value) {
        setAttributeInternal(ESCORTID, value);
    }

    /**
     * Gets the attribute value for RcvFlag, using the alias name RcvFlag.
     * @return the RcvFlag
     */
    public String getRcvFlag() {
        return (String)getAttributeInternal(RCVFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for RcvFlag.
     * @param value value to set the RcvFlag
     */
    public void setRcvFlag(String value) {
        setAttributeInternal(RCVFLAG, value);
    }

    /**
     * Gets the attribute value for DepartureTime, using the alias name DepartureTime.
     * @return the DepartureTime
     */
    public Date getDepartureTime() {
        return (Date)getAttributeInternal(DEPARTURETIME);
    }

    /**
     * Sets <code>value</code> as the attribute value for DepartureTime.
     * @param value value to set the DepartureTime
     */
    public void setDepartureTime(Date value) {
        setAttributeInternal(DEPARTURETIME, value);
    }

    /**
     * Gets the attribute value for EmptyCarton, using the alias name EmptyCarton.
     * @return the EmptyCarton
     */
    public String getEmptyCarton() {
        return (String)getAttributeInternal(EMPTYCARTON);
    }

    /**
     * Sets <code>value</code> as the attribute value for EmptyCarton.
     * @param value value to set the EmptyCarton
     */
    public void setEmptyCarton(String value) {
        setAttributeInternal(EMPTYCARTON, value);
    }

    /**
     * Gets the attribute value for GumTap, using the alias name GumTap.
     * @return the GumTap
     */
    public String getGumTap() {
        return (String)getAttributeInternal(GUMTAP);
    }

    /**
     * Sets <code>value</code> as the attribute value for GumTap.
     * @param value value to set the GumTap
     */
    public void setGumTap(String value) {
        setAttributeInternal(GUMTAP, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getInlandTransportLinesEO() {
        return (RowIterator)getAttributeInternal(INLANDTRANSPORTLINESEO);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getCommercalTabEo() {
        return (RowIterator)getAttributeInternal(COMMERCALTABEO);
    }


    /**
     * @param inlandTransHeaderId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number inlandTransHeaderId) {
        return new Key(new Object[]{inlandTransHeaderId});
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    
    protected void create(AttributeList attributeList) {
            super.create(attributeList);
            /* Sequence Generation Code of Header by PwC */  
            oracle.jbo.server.SequenceImpl s = new oracle.jbo.server.SequenceImpl("IEDOC_EXP_INLAND_TRAN_HEAD_S",getDBTransaction());          
            oracle.jbo.domain.Number sVal = s.getSequenceNumber();          
            setInlandTransHeaderId(sVal);
            /* End Sequence Generation Code of Header by PwC */
        }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        Map sessionScope = ADFContext.getCurrent().getSessionScope();   
                String user = (String)sessionScope.get("userId");
        String orgId = (String)sessionScope.get("orgId");
               // System.out.println("Document No -->"+getSrNoString());
                if(DML_UPDATE == operation){
                    try {
                        setLastUpdateDate((Date)Date.getCurrentDate()); 
                        setLastUpdatedBy(new oracle.jbo.domain.Number(user));
                    } catch (SQLException f) {
                        System.out.println(f.getMessage());
                    }
                }
                else if (DML_INSERT == operation){
                    try {
                        //setPercostingNumber(new oracle.jbo.domain.Number(getSrNoString()));
                        setCreationDate((Date)Date.getCurrentDate());  
                        setCreatedBy(new oracle.jbo.domain.Number(user));
//                        if(!orgId.equals("null"))
//                        setOrgId(new oracle.jbo.domain.Number(orgId));
                    } catch (SQLException f) {
                        ;
                    }
                }

        
        super.doDML(operation, e);
    }
}
