package mnj.ont.model.entities;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.ViewObject;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jan 09 15:31:21 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InlandTransportLinesEOImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        InlandTransLinesId {
            public Object get(InlandTransportLinesEOImpl obj) {
                return obj.getInlandTransLinesId();
            }

            public void put(InlandTransportLinesEOImpl obj, Object value) {
                obj.setInlandTransLinesId((Number)value);
            }
        }
        ,
        InlandTransHeaderId {
            public Object get(InlandTransportLinesEOImpl obj) {
                return obj.getInlandTransHeaderId();
            }

            public void put(InlandTransportLinesEOImpl obj, Object value) {
                obj.setInlandTransHeaderId((Number)value);
            }
        }
        ,
        Style {
            public Object get(InlandTransportLinesEOImpl obj) {
                return obj.getStyle();
            }

            public void put(InlandTransportLinesEOImpl obj, Object value) {
                obj.setStyle((String)value);
            }
        }
        ,
        OrderBpo {
            public Object get(InlandTransportLinesEOImpl obj) {
                return obj.getOrderBpo();
            }

            public void put(InlandTransportLinesEOImpl obj, Object value) {
                obj.setOrderBpo((String)value);
            }
        }
        ,
        DcpoNo {
            public Object get(InlandTransportLinesEOImpl obj) {
                return obj.getDcpoNo();
            }

            public void put(InlandTransportLinesEOImpl obj, Object value) {
                obj.setDcpoNo((String)value);
            }
        }
        ,
        ItemId {
            public Object get(InlandTransportLinesEOImpl obj) {
                return obj.getItemId();
            }

            public void put(InlandTransportLinesEOImpl obj, Object value) {
                obj.setItemId((Number)value);
            }
        }
        ,
        CartonQuantity {
            public Object get(InlandTransportLinesEOImpl obj) {
                return obj.getCartonQuantity();
            }

            public void put(InlandTransportLinesEOImpl obj, Object value) {
                obj.setCartonQuantity((Number)value);
            }
        }
        ,
        CartonAssign {
            public Object get(InlandTransportLinesEOImpl obj) {
                return obj.getCartonAssign();
            }

            public void put(InlandTransportLinesEOImpl obj, Object value) {
                obj.setCartonAssign((Number)value);
            }
        }
        ,
        CfsName {
            public Object get(InlandTransportLinesEOImpl obj) {
                return obj.getCfsName();
            }

            public void put(InlandTransportLinesEOImpl obj, Object value) {
                obj.setCfsName((String)value);
            }
        }
        ,
        CfName {
            public Object get(InlandTransportLinesEOImpl obj) {
                return obj.getCfName();
            }

            public void put(InlandTransportLinesEOImpl obj, Object value) {
                obj.setCfName((String)value);
            }
        }
        ,
        ForwardErName {
            public Object get(InlandTransportLinesEOImpl obj) {
                return obj.getForwardErName();
            }

            public void put(InlandTransportLinesEOImpl obj, Object value) {
                obj.setForwardErName((String)value);
            }
        }
        ,
        InvoiceNo {
            public Object get(InlandTransportLinesEOImpl obj) {
                return obj.getInvoiceNo();
            }

            public void put(InlandTransportLinesEOImpl obj, Object value) {
                obj.setInvoiceNo((String)value);
            }
        }
        ,
        LastUpdateLogin {
            public Object get(InlandTransportLinesEOImpl obj) {
                return obj.getLastUpdateLogin();
            }

            public void put(InlandTransportLinesEOImpl obj, Object value) {
                obj.setLastUpdateLogin((Number)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(InlandTransportLinesEOImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(InlandTransportLinesEOImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(InlandTransportLinesEOImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(InlandTransportLinesEOImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(InlandTransportLinesEOImpl obj) {
                return obj.getCreationDate();
            }

            public void put(InlandTransportLinesEOImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(InlandTransportLinesEOImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(InlandTransportLinesEOImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        Attribute1 {
            public Object get(InlandTransportLinesEOImpl obj) {
                return obj.getAttribute1();
            }

            public void put(InlandTransportLinesEOImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(InlandTransportLinesEOImpl obj) {
                return obj.getAttribute2();
            }

            public void put(InlandTransportLinesEOImpl obj, Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(InlandTransportLinesEOImpl obj) {
                return obj.getAttribute3();
            }

            public void put(InlandTransportLinesEOImpl obj, Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(InlandTransportLinesEOImpl obj) {
                return obj.getAttribute4();
            }

            public void put(InlandTransportLinesEOImpl obj, Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(InlandTransportLinesEOImpl obj) {
                return obj.getAttribute5();
            }

            public void put(InlandTransportLinesEOImpl obj, Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(InlandTransportLinesEOImpl obj) {
                return obj.getAttribute6();
            }

            public void put(InlandTransportLinesEOImpl obj, Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(InlandTransportLinesEOImpl obj) {
                return obj.getAttribute7();
            }

            public void put(InlandTransportLinesEOImpl obj, Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(InlandTransportLinesEOImpl obj) {
                return obj.getAttribute8();
            }

            public void put(InlandTransportLinesEOImpl obj, Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(InlandTransportLinesEOImpl obj) {
                return obj.getAttribute9();
            }

            public void put(InlandTransportLinesEOImpl obj, Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        Attribute10 {
            public Object get(InlandTransportLinesEOImpl obj) {
                return obj.getAttribute10();
            }

            public void put(InlandTransportLinesEOImpl obj, Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        Attribute11 {
            public Object get(InlandTransportLinesEOImpl obj) {
                return obj.getAttribute11();
            }

            public void put(InlandTransportLinesEOImpl obj, Object value) {
                obj.setAttribute11((String)value);
            }
        }
        ,
        Attribute12 {
            public Object get(InlandTransportLinesEOImpl obj) {
                return obj.getAttribute12();
            }

            public void put(InlandTransportLinesEOImpl obj, Object value) {
                obj.setAttribute12((String)value);
            }
        }
        ,
        Attribute13 {
            public Object get(InlandTransportLinesEOImpl obj) {
                return obj.getAttribute13();
            }

            public void put(InlandTransportLinesEOImpl obj, Object value) {
                obj.setAttribute13((String)value);
            }
        }
        ,
        Attribute14 {
            public Object get(InlandTransportLinesEOImpl obj) {
                return obj.getAttribute14();
            }

            public void put(InlandTransportLinesEOImpl obj, Object value) {
                obj.setAttribute14((String)value);
            }
        }
        ,
        Attribute15 {
            public Object get(InlandTransportLinesEOImpl obj) {
                return obj.getAttribute15();
            }

            public void put(InlandTransportLinesEOImpl obj, Object value) {
                obj.setAttribute15((String)value);
            }
        }
        ,
        Attribute16 {
            public Object get(InlandTransportLinesEOImpl obj) {
                return obj.getAttribute16();
            }

            public void put(InlandTransportLinesEOImpl obj, Object value) {
                obj.setAttribute16((String)value);
            }
        }
        ,
        Attribute17 {
            public Object get(InlandTransportLinesEOImpl obj) {
                return obj.getAttribute17();
            }

            public void put(InlandTransportLinesEOImpl obj, Object value) {
                obj.setAttribute17((String)value);
            }
        }
        ,
        Attribute18 {
            public Object get(InlandTransportLinesEOImpl obj) {
                return obj.getAttribute18();
            }

            public void put(InlandTransportLinesEOImpl obj, Object value) {
                obj.setAttribute18((String)value);
            }
        }
        ,
        Attribute19 {
            public Object get(InlandTransportLinesEOImpl obj) {
                return obj.getAttribute19();
            }

            public void put(InlandTransportLinesEOImpl obj, Object value) {
                obj.setAttribute19((String)value);
            }
        }
        ,
        Attribute20 {
            public Object get(InlandTransportLinesEOImpl obj) {
                return obj.getAttribute20();
            }

            public void put(InlandTransportLinesEOImpl obj, Object value) {
                obj.setAttribute20((String)value);
            }
        }
        ,
        AttributeNum1 {
            public Object get(InlandTransportLinesEOImpl obj) {
                return obj.getAttributeNum1();
            }

            public void put(InlandTransportLinesEOImpl obj, Object value) {
                obj.setAttributeNum1((Number)value);
            }
        }
        ,
        AttributeNum2 {
            public Object get(InlandTransportLinesEOImpl obj) {
                return obj.getAttributeNum2();
            }

            public void put(InlandTransportLinesEOImpl obj, Object value) {
                obj.setAttributeNum2((Number)value);
            }
        }
        ,
        AttributeNum3 {
            public Object get(InlandTransportLinesEOImpl obj) {
                return obj.getAttributeNum3();
            }

            public void put(InlandTransportLinesEOImpl obj, Object value) {
                obj.setAttributeNum3((Number)value);
            }
        }
        ,
        AttributeNum4 {
            public Object get(InlandTransportLinesEOImpl obj) {
                return obj.getAttributeNum4();
            }

            public void put(InlandTransportLinesEOImpl obj, Object value) {
                obj.setAttributeNum4((Number)value);
            }
        }
        ,
        AttributeNum5 {
            public Object get(InlandTransportLinesEOImpl obj) {
                return obj.getAttributeNum5();
            }

            public void put(InlandTransportLinesEOImpl obj, Object value) {
                obj.setAttributeNum5((Number)value);
            }
        }
        ,
        AttributeNum6 {
            public Object get(InlandTransportLinesEOImpl obj) {
                return obj.getAttributeNum6();
            }

            public void put(InlandTransportLinesEOImpl obj, Object value) {
                obj.setAttributeNum6((Number)value);
            }
        }
        ,
        AttributeNum7 {
            public Object get(InlandTransportLinesEOImpl obj) {
                return obj.getAttributeNum7();
            }

            public void put(InlandTransportLinesEOImpl obj, Object value) {
                obj.setAttributeNum7((Number)value);
            }
        }
        ,
        AttributeNum8 {
            public Object get(InlandTransportLinesEOImpl obj) {
                return obj.getAttributeNum8();
            }

            public void put(InlandTransportLinesEOImpl obj, Object value) {
                obj.setAttributeNum8((Number)value);
            }
        }
        ,
        AttributeNum9 {
            public Object get(InlandTransportLinesEOImpl obj) {
                return obj.getAttributeNum9();
            }

            public void put(InlandTransportLinesEOImpl obj, Object value) {
                obj.setAttributeNum9((Number)value);
            }
        }
        ,
        AttributeNum10 {
            public Object get(InlandTransportLinesEOImpl obj) {
                return obj.getAttributeNum10();
            }

            public void put(InlandTransportLinesEOImpl obj, Object value) {
                obj.setAttributeNum10((Number)value);
            }
        }
        ,
        AttributeDate1 {
            public Object get(InlandTransportLinesEOImpl obj) {
                return obj.getAttributeDate1();
            }

            public void put(InlandTransportLinesEOImpl obj, Object value) {
                obj.setAttributeDate1((Date)value);
            }
        }
        ,
        AttributeDate2 {
            public Object get(InlandTransportLinesEOImpl obj) {
                return obj.getAttributeDate2();
            }

            public void put(InlandTransportLinesEOImpl obj, Object value) {
                obj.setAttributeDate2((Date)value);
            }
        }
        ,
        AttributeDate3 {
            public Object get(InlandTransportLinesEOImpl obj) {
                return obj.getAttributeDate3();
            }

            public void put(InlandTransportLinesEOImpl obj, Object value) {
                obj.setAttributeDate3((Date)value);
            }
        }
        ,
        AttributeDate4 {
            public Object get(InlandTransportLinesEOImpl obj) {
                return obj.getAttributeDate4();
            }

            public void put(InlandTransportLinesEOImpl obj, Object value) {
                obj.setAttributeDate4((Date)value);
            }
        }
        ,
        AttributeDate5 {
            public Object get(InlandTransportLinesEOImpl obj) {
                return obj.getAttributeDate5();
            }

            public void put(InlandTransportLinesEOImpl obj, Object value) {
                obj.setAttributeDate5((Date)value);
            }
        }
        ,
        TotalCbm {
            public Object get(InlandTransportLinesEOImpl obj) {
                return obj.getTotalCbm();
            }

            public void put(InlandTransportLinesEOImpl obj, Object value) {
                obj.setTotalCbm((Number)value);
            }
        }
        ,
        BalancePcs {
            public Object get(InlandTransportLinesEOImpl obj) {
                return obj.getBalancePcs();
            }

            public void put(InlandTransportLinesEOImpl obj, Object value) {
                obj.setBalancePcs((Number)value);
            }
        }
        ,
        AssignedPcs {
            public Object get(InlandTransportLinesEOImpl obj) {
                return obj.getAssignedPcs();
            }

            public void put(InlandTransportLinesEOImpl obj, Object value) {
                obj.setAssignedPcs((Number)value);
            }
        }
        ,
        AssignCbm {
            public Object get(InlandTransportLinesEOImpl obj) {
                return obj.getAssignCbm();
            }

            public void put(InlandTransportLinesEOImpl obj, Object value) {
                obj.setAssignCbm((Number)value);
            }
        }
        ,
        PackList {
            public Object get(InlandTransportLinesEOImpl obj) {
                return obj.getPackList();
            }

            public void put(InlandTransportLinesEOImpl obj, Object value) {
                obj.setPackList((Number)value);
            }
        }
        ,
        StyleNo {
            public Object get(InlandTransportLinesEOImpl obj) {
                return obj.getStyleNo();
            }

            public void put(InlandTransportLinesEOImpl obj, Object value) {
                obj.setStyleNo((String)value);
            }
        }
        ,
        CurrentStyle {
            public Object get(InlandTransportLinesEOImpl obj) {
                return obj.getCurrentStyle();
            }

            public void put(InlandTransportLinesEOImpl obj, Object value) {
                obj.setCurrentStyle((String)value);
            }
        }
        ,
        CurrentStyleNo {
            public Object get(InlandTransportLinesEOImpl obj) {
                return obj.getCurrentStyleNo();
            }

            public void put(InlandTransportLinesEOImpl obj, Object value) {
                obj.setCurrentStyleNo((String)value);
            }
        }
        ,
        SubContractOrg {
            public Object get(InlandTransportLinesEOImpl obj) {
                return obj.getSubContractOrg();
            }

            public void put(InlandTransportLinesEOImpl obj, Object value) {
                obj.setSubContractOrg((Number)value);
            }
        }
        ,
        PackedCartonQty {
            public Object get(InlandTransportLinesEOImpl obj) {
                return obj.getPackedCartonQty();
            }

            public void put(InlandTransportLinesEOImpl obj, Object value) {
                obj.setPackedCartonQty((Number)value);
            }
        }
        ,
        PackedPcsQty {
            public Object get(InlandTransportLinesEOImpl obj) {
                return obj.getPackedPcsQty();
            }

            public void put(InlandTransportLinesEOImpl obj, Object value) {
                obj.setPackedPcsQty((Number)value);
            }
        }
        ,
        InlandTransportHeaderEO {
            public Object get(InlandTransportLinesEOImpl obj) {
                return obj.getInlandTransportHeaderEO();
            }

            public void put(InlandTransportLinesEOImpl obj, Object value) {
                obj.setInlandTransportHeaderEO((InlandTransportHeaderEOImpl)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(InlandTransportLinesEOImpl object);

        public abstract void put(InlandTransportLinesEOImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int INLANDTRANSLINESID = AttributesEnum.InlandTransLinesId.index();
    public static final int INLANDTRANSHEADERID = AttributesEnum.InlandTransHeaderId.index();
    public static final int STYLE = AttributesEnum.Style.index();
    public static final int ORDERBPO = AttributesEnum.OrderBpo.index();
    public static final int DCPONO = AttributesEnum.DcpoNo.index();
    public static final int ITEMID = AttributesEnum.ItemId.index();
    public static final int CARTONQUANTITY = AttributesEnum.CartonQuantity.index();
    public static final int CARTONASSIGN = AttributesEnum.CartonAssign.index();
    public static final int CFSNAME = AttributesEnum.CfsName.index();
    public static final int CFNAME = AttributesEnum.CfName.index();
    public static final int FORWARDERNAME = AttributesEnum.ForwardErName.index();
    public static final int INVOICENO = AttributesEnum.InvoiceNo.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int ATTRIBUTE11 = AttributesEnum.Attribute11.index();
    public static final int ATTRIBUTE12 = AttributesEnum.Attribute12.index();
    public static final int ATTRIBUTE13 = AttributesEnum.Attribute13.index();
    public static final int ATTRIBUTE14 = AttributesEnum.Attribute14.index();
    public static final int ATTRIBUTE15 = AttributesEnum.Attribute15.index();
    public static final int ATTRIBUTE16 = AttributesEnum.Attribute16.index();
    public static final int ATTRIBUTE17 = AttributesEnum.Attribute17.index();
    public static final int ATTRIBUTE18 = AttributesEnum.Attribute18.index();
    public static final int ATTRIBUTE19 = AttributesEnum.Attribute19.index();
    public static final int ATTRIBUTE20 = AttributesEnum.Attribute20.index();
    public static final int ATTRIBUTENUM1 = AttributesEnum.AttributeNum1.index();
    public static final int ATTRIBUTENUM2 = AttributesEnum.AttributeNum2.index();
    public static final int ATTRIBUTENUM3 = AttributesEnum.AttributeNum3.index();
    public static final int ATTRIBUTENUM4 = AttributesEnum.AttributeNum4.index();
    public static final int ATTRIBUTENUM5 = AttributesEnum.AttributeNum5.index();
    public static final int ATTRIBUTENUM6 = AttributesEnum.AttributeNum6.index();
    public static final int ATTRIBUTENUM7 = AttributesEnum.AttributeNum7.index();
    public static final int ATTRIBUTENUM8 = AttributesEnum.AttributeNum8.index();
    public static final int ATTRIBUTENUM9 = AttributesEnum.AttributeNum9.index();
    public static final int ATTRIBUTENUM10 = AttributesEnum.AttributeNum10.index();
    public static final int ATTRIBUTEDATE1 = AttributesEnum.AttributeDate1.index();
    public static final int ATTRIBUTEDATE2 = AttributesEnum.AttributeDate2.index();
    public static final int ATTRIBUTEDATE3 = AttributesEnum.AttributeDate3.index();
    public static final int ATTRIBUTEDATE4 = AttributesEnum.AttributeDate4.index();
    public static final int ATTRIBUTEDATE5 = AttributesEnum.AttributeDate5.index();
    public static final int TOTALCBM = AttributesEnum.TotalCbm.index();
    public static final int BALANCEPCS = AttributesEnum.BalancePcs.index();
    public static final int ASSIGNEDPCS = AttributesEnum.AssignedPcs.index();
    public static final int ASSIGNCBM = AttributesEnum.AssignCbm.index();
    public static final int PACKLIST = AttributesEnum.PackList.index();
    public static final int STYLENO = AttributesEnum.StyleNo.index();
    public static final int CURRENTSTYLE = AttributesEnum.CurrentStyle.index();
    public static final int CURRENTSTYLENO = AttributesEnum.CurrentStyleNo.index();
    public static final int SUBCONTRACTORG = AttributesEnum.SubContractOrg.index();
    public static final int PACKEDCARTONQTY = AttributesEnum.PackedCartonQty.index();
    public static final int PACKEDPCSQTY = AttributesEnum.PackedPcsQty.index();
    public static final int INLANDTRANSPORTHEADEREO = AttributesEnum.InlandTransportHeaderEO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public InlandTransportLinesEOImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("mnj.ont.model.entities.InlandTransportLinesEO");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for InlandTransLinesId, using the alias name InlandTransLinesId.
     * @return the InlandTransLinesId
     */
    public Number getInlandTransLinesId() {
        return (Number)getAttributeInternal(INLANDTRANSLINESID);
    }

    /**
     * Sets <code>value</code> as the attribute value for InlandTransLinesId.
     * @param value value to set the InlandTransLinesId
     */
    public void setInlandTransLinesId(Number value) {
        setAttributeInternal(INLANDTRANSLINESID, value);
    }

    /**
     * Gets the attribute value for InlandTransHeaderId, using the alias name InlandTransHeaderId.
     * @return the InlandTransHeaderId
     */
    public Number getInlandTransHeaderId() {
        return (Number)getAttributeInternal(INLANDTRANSHEADERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for InlandTransHeaderId.
     * @param value value to set the InlandTransHeaderId
     */
    public void setInlandTransHeaderId(Number value) {
        setAttributeInternal(INLANDTRANSHEADERID, value);
    }

    /**
     * Gets the attribute value for Style, using the alias name Style.
     * @return the Style
     */
    public String getStyle() {
        return (String)getAttributeInternal(STYLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Style.
     * @param value value to set the Style
     */
    public void setStyle(String value) {
        setAttributeInternal(STYLE, value);
    }

    /**
     * Gets the attribute value for OrderBpo, using the alias name OrderBpo.
     * @return the OrderBpo
     */
    public String getOrderBpo() {
        return (String)getAttributeInternal(ORDERBPO);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrderBpo.
     * @param value value to set the OrderBpo
     */
    public void setOrderBpo(String value) {
        setAttributeInternal(ORDERBPO, value);
    }

    /**
     * Gets the attribute value for DcpoNo, using the alias name DcpoNo.
     * @return the DcpoNo
     */
    public String getDcpoNo() {
        return (String)getAttributeInternal(DCPONO);
    }

    /**
     * Sets <code>value</code> as the attribute value for DcpoNo.
     * @param value value to set the DcpoNo
     */
    public void setDcpoNo(String value) {
        setAttributeInternal(DCPONO, value);
    }

    /**
     * Gets the attribute value for ItemId, using the alias name ItemId.
     * @return the ItemId
     */
    public Number getItemId() {
        return (Number)getAttributeInternal(ITEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItemId.
     * @param value value to set the ItemId
     */
    public void setItemId(Number value) {
        setAttributeInternal(ITEMID, value);
    }

    /**
     * Gets the attribute value for CartonQuantity, using the alias name CartonQuantity.
     * @return the CartonQuantity
     */
    public Number getCartonQuantity() {
        return (Number)getAttributeInternal(CARTONQUANTITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CartonQuantity.
     * @param value value to set the CartonQuantity
     */
    public void setCartonQuantity(Number value) {
        setAttributeInternal(CARTONQUANTITY, value);
    }

    /**
     * Gets the attribute value for CartonAssign, using the alias name CartonAssign.
     * @return the CartonAssign
     */
    public Number getCartonAssign() {
        return (Number)getAttributeInternal(CARTONASSIGN);
    }

    /**
     * Sets <code>value</code> as the attribute value for CartonAssign.
     * @param value value to set the CartonAssign
     */
    public void setCartonAssign(Number value) {
        setAttributeInternal(CARTONASSIGN, value);
    }

    /**
     * Gets the attribute value for CfsName, using the alias name CfsName.
     * @return the CfsName
     */
    public String getCfsName() {
        return (String)getAttributeInternal(CFSNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for CfsName.
     * @param value value to set the CfsName
     */
    public void setCfsName(String value) {
        setAttributeInternal(CFSNAME, value);
    }

    /**
     * Gets the attribute value for CfName, using the alias name CfName.
     * @return the CfName
     */
    public String getCfName() {
        return (String)getAttributeInternal(CFNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for CfName.
     * @param value value to set the CfName
     */
    public void setCfName(String value) {
        setAttributeInternal(CFNAME, value);
    }

    /**
     * Gets the attribute value for ForwardErName, using the alias name ForwardErName.
     * @return the ForwardErName
     */
    public String getForwardErName() {
        return (String)getAttributeInternal(FORWARDERNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for ForwardErName.
     * @param value value to set the ForwardErName
     */
    public void setForwardErName(String value) {
        setAttributeInternal(FORWARDERNAME, value);
    }

    /**
     * Gets the attribute value for InvoiceNo, using the alias name InvoiceNo.
     * @return the InvoiceNo
     */
    public String getInvoiceNo() {
        return (String)getAttributeInternal(INVOICENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for InvoiceNo.
     * @param value value to set the InvoiceNo
     */
    public void setInvoiceNo(String value) {
        setAttributeInternal(INVOICENO, value);
    }

    /**
     * Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin.
     * @return the LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number)getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateLogin.
     * @param value value to set the LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateDate.
     * @param value value to set the LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for Attribute1, using the alias name Attribute1.
     * @return the Attribute1
     */
    public String getAttribute1() {
        return (String)getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute1.
     * @param value value to set the Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for Attribute2, using the alias name Attribute2.
     * @return the Attribute2
     */
    public String getAttribute2() {
        return (String)getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute2.
     * @param value value to set the Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for Attribute3, using the alias name Attribute3.
     * @return the Attribute3
     */
    public String getAttribute3() {
        return (String)getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute3.
     * @param value value to set the Attribute3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for Attribute4, using the alias name Attribute4.
     * @return the Attribute4
     */
    public String getAttribute4() {
        return (String)getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute4.
     * @param value value to set the Attribute4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for Attribute5, using the alias name Attribute5.
     * @return the Attribute5
     */
    public String getAttribute5() {
        return (String)getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute5.
     * @param value value to set the Attribute5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for Attribute6, using the alias name Attribute6.
     * @return the Attribute6
     */
    public String getAttribute6() {
        return (String)getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute6.
     * @param value value to set the Attribute6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for Attribute7, using the alias name Attribute7.
     * @return the Attribute7
     */
    public String getAttribute7() {
        return (String)getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute7.
     * @param value value to set the Attribute7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for Attribute8, using the alias name Attribute8.
     * @return the Attribute8
     */
    public String getAttribute8() {
        return (String)getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute8.
     * @param value value to set the Attribute8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for Attribute9, using the alias name Attribute9.
     * @return the Attribute9
     */
    public String getAttribute9() {
        return (String)getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute9.
     * @param value value to set the Attribute9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for Attribute10, using the alias name Attribute10.
     * @return the Attribute10
     */
    public String getAttribute10() {
        return (String)getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute10.
     * @param value value to set the Attribute10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for Attribute11, using the alias name Attribute11.
     * @return the Attribute11
     */
    public String getAttribute11() {
        return (String)getAttributeInternal(ATTRIBUTE11);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute11.
     * @param value value to set the Attribute11
     */
    public void setAttribute11(String value) {
        setAttributeInternal(ATTRIBUTE11, value);
    }

    /**
     * Gets the attribute value for Attribute12, using the alias name Attribute12.
     * @return the Attribute12
     */
    public String getAttribute12() {
        return (String)getAttributeInternal(ATTRIBUTE12);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute12.
     * @param value value to set the Attribute12
     */
    public void setAttribute12(String value) {
        setAttributeInternal(ATTRIBUTE12, value);
    }

    /**
     * Gets the attribute value for Attribute13, using the alias name Attribute13.
     * @return the Attribute13
     */
    public String getAttribute13() {
        return (String)getAttributeInternal(ATTRIBUTE13);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute13.
     * @param value value to set the Attribute13
     */
    public void setAttribute13(String value) {
        setAttributeInternal(ATTRIBUTE13, value);
    }

    /**
     * Gets the attribute value for Attribute14, using the alias name Attribute14.
     * @return the Attribute14
     */
    public String getAttribute14() {
        return (String)getAttributeInternal(ATTRIBUTE14);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute14.
     * @param value value to set the Attribute14
     */
    public void setAttribute14(String value) {
        setAttributeInternal(ATTRIBUTE14, value);
    }

    /**
     * Gets the attribute value for Attribute15, using the alias name Attribute15.
     * @return the Attribute15
     */
    public String getAttribute15() {
        return (String)getAttributeInternal(ATTRIBUTE15);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute15.
     * @param value value to set the Attribute15
     */
    public void setAttribute15(String value) {
        setAttributeInternal(ATTRIBUTE15, value);
    }

    /**
     * Gets the attribute value for Attribute16, using the alias name Attribute16.
     * @return the Attribute16
     */
    public String getAttribute16() {
        return (String)getAttributeInternal(ATTRIBUTE16);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute16.
     * @param value value to set the Attribute16
     */
    public void setAttribute16(String value) {
        setAttributeInternal(ATTRIBUTE16, value);
    }

    /**
     * Gets the attribute value for Attribute17, using the alias name Attribute17.
     * @return the Attribute17
     */
    public String getAttribute17() {
        return (String)getAttributeInternal(ATTRIBUTE17);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute17.
     * @param value value to set the Attribute17
     */
    public void setAttribute17(String value) {
        setAttributeInternal(ATTRIBUTE17, value);
    }

    /**
     * Gets the attribute value for Attribute18, using the alias name Attribute18.
     * @return the Attribute18
     */
    public String getAttribute18() {
        return (String)getAttributeInternal(ATTRIBUTE18);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute18.
     * @param value value to set the Attribute18
     */
    public void setAttribute18(String value) {
        setAttributeInternal(ATTRIBUTE18, value);
    }

    /**
     * Gets the attribute value for Attribute19, using the alias name Attribute19.
     * @return the Attribute19
     */
    public String getAttribute19() {
        return (String)getAttributeInternal(ATTRIBUTE19);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute19.
     * @param value value to set the Attribute19
     */
    public void setAttribute19(String value) {
        setAttributeInternal(ATTRIBUTE19, value);
    }

    /**
     * Gets the attribute value for Attribute20, using the alias name Attribute20.
     * @return the Attribute20
     */
    public String getAttribute20() {
        return (String)getAttributeInternal(ATTRIBUTE20);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute20.
     * @param value value to set the Attribute20
     */
    public void setAttribute20(String value) {
        setAttributeInternal(ATTRIBUTE20, value);
    }

    /**
     * Gets the attribute value for AttributeNum1, using the alias name AttributeNum1.
     * @return the AttributeNum1
     */
    public Number getAttributeNum1() {
        return (Number)getAttributeInternal(ATTRIBUTENUM1);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeNum1.
     * @param value value to set the AttributeNum1
     */
    public void setAttributeNum1(Number value) {
        setAttributeInternal(ATTRIBUTENUM1, value);
    }

    /**
     * Gets the attribute value for AttributeNum2, using the alias name AttributeNum2.
     * @return the AttributeNum2
     */
    public Number getAttributeNum2() {
        return (Number)getAttributeInternal(ATTRIBUTENUM2);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeNum2.
     * @param value value to set the AttributeNum2
     */
    public void setAttributeNum2(Number value) {
        setAttributeInternal(ATTRIBUTENUM2, value);
    }

    /**
     * Gets the attribute value for AttributeNum3, using the alias name AttributeNum3.
     * @return the AttributeNum3
     */
    public Number getAttributeNum3() {
        return (Number)getAttributeInternal(ATTRIBUTENUM3);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeNum3.
     * @param value value to set the AttributeNum3
     */
    public void setAttributeNum3(Number value) {
        setAttributeInternal(ATTRIBUTENUM3, value);
    }

    /**
     * Gets the attribute value for AttributeNum4, using the alias name AttributeNum4.
     * @return the AttributeNum4
     */
    public Number getAttributeNum4() {
        return (Number)getAttributeInternal(ATTRIBUTENUM4);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeNum4.
     * @param value value to set the AttributeNum4
     */
    public void setAttributeNum4(Number value) {
        setAttributeInternal(ATTRIBUTENUM4, value);
    }

    /**
     * Gets the attribute value for AttributeNum5, using the alias name AttributeNum5.
     * @return the AttributeNum5
     */
    public Number getAttributeNum5() {
        return (Number)getAttributeInternal(ATTRIBUTENUM5);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeNum5.
     * @param value value to set the AttributeNum5
     */
    public void setAttributeNum5(Number value) {
        setAttributeInternal(ATTRIBUTENUM5, value);
    }

    /**
     * Gets the attribute value for AttributeNum6, using the alias name AttributeNum6.
     * @return the AttributeNum6
     */
    public Number getAttributeNum6() {
        return (Number)getAttributeInternal(ATTRIBUTENUM6);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeNum6.
     * @param value value to set the AttributeNum6
     */
    public void setAttributeNum6(Number value) {
        setAttributeInternal(ATTRIBUTENUM6, value);
    }

    /**
     * Gets the attribute value for AttributeNum7, using the alias name AttributeNum7.
     * @return the AttributeNum7
     */
    public Number getAttributeNum7() {
        return (Number)getAttributeInternal(ATTRIBUTENUM7);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeNum7.
     * @param value value to set the AttributeNum7
     */
    public void setAttributeNum7(Number value) {
        setAttributeInternal(ATTRIBUTENUM7, value);
    }

    /**
     * Gets the attribute value for AttributeNum8, using the alias name AttributeNum8.
     * @return the AttributeNum8
     */
    public Number getAttributeNum8() {
        return (Number)getAttributeInternal(ATTRIBUTENUM8);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeNum8.
     * @param value value to set the AttributeNum8
     */
    public void setAttributeNum8(Number value) {
        setAttributeInternal(ATTRIBUTENUM8, value);
    }

    /**
     * Gets the attribute value for AttributeNum9, using the alias name AttributeNum9.
     * @return the AttributeNum9
     */
    public Number getAttributeNum9() {
        return (Number)getAttributeInternal(ATTRIBUTENUM9);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeNum9.
     * @param value value to set the AttributeNum9
     */
    public void setAttributeNum9(Number value) {
        setAttributeInternal(ATTRIBUTENUM9, value);
    }

    /**
     * Gets the attribute value for AttributeNum10, using the alias name AttributeNum10.
     * @return the AttributeNum10
     */
    public Number getAttributeNum10() {
        return (Number)getAttributeInternal(ATTRIBUTENUM10);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeNum10.
     * @param value value to set the AttributeNum10
     */
    public void setAttributeNum10(Number value) {
        setAttributeInternal(ATTRIBUTENUM10, value);
    }

    /**
     * Gets the attribute value for AttributeDate1, using the alias name AttributeDate1.
     * @return the AttributeDate1
     */
    public Date getAttributeDate1() {
        return (Date)getAttributeInternal(ATTRIBUTEDATE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeDate1.
     * @param value value to set the AttributeDate1
     */
    public void setAttributeDate1(Date value) {
        setAttributeInternal(ATTRIBUTEDATE1, value);
    }

    /**
     * Gets the attribute value for AttributeDate2, using the alias name AttributeDate2.
     * @return the AttributeDate2
     */
    public Date getAttributeDate2() {
        return (Date)getAttributeInternal(ATTRIBUTEDATE2);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeDate2.
     * @param value value to set the AttributeDate2
     */
    public void setAttributeDate2(Date value) {
        setAttributeInternal(ATTRIBUTEDATE2, value);
    }

    /**
     * Gets the attribute value for AttributeDate3, using the alias name AttributeDate3.
     * @return the AttributeDate3
     */
    public Date getAttributeDate3() {
        return (Date)getAttributeInternal(ATTRIBUTEDATE3);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeDate3.
     * @param value value to set the AttributeDate3
     */
    public void setAttributeDate3(Date value) {
        setAttributeInternal(ATTRIBUTEDATE3, value);
    }

    /**
     * Gets the attribute value for AttributeDate4, using the alias name AttributeDate4.
     * @return the AttributeDate4
     */
    public Date getAttributeDate4() {
        return (Date)getAttributeInternal(ATTRIBUTEDATE4);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeDate4.
     * @param value value to set the AttributeDate4
     */
    public void setAttributeDate4(Date value) {
        setAttributeInternal(ATTRIBUTEDATE4, value);
    }

    /**
     * Gets the attribute value for AttributeDate5, using the alias name AttributeDate5.
     * @return the AttributeDate5
     */
    public Date getAttributeDate5() {
        return (Date)getAttributeInternal(ATTRIBUTEDATE5);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeDate5.
     * @param value value to set the AttributeDate5
     */
    public void setAttributeDate5(Date value) {
        setAttributeInternal(ATTRIBUTEDATE5, value);
    }

    /**
     * Gets the attribute value for TotalCbm, using the alias name TotalCbm.
     * @return the TotalCbm
     */
    public Number getTotalCbm() {
        return (Number)getAttributeInternal(TOTALCBM);
    }

    /**
     * Sets <code>value</code> as the attribute value for TotalCbm.
     * @param value value to set the TotalCbm
     */
    public void setTotalCbm(Number value) {
        setAttributeInternal(TOTALCBM, value);
    }

    /**
     * Gets the attribute value for BalancePcs, using the alias name BalancePcs.
     * @return the BalancePcs
     */
    public Number getBalancePcs() {
        return (Number)getAttributeInternal(BALANCEPCS);
    }

    /**
     * Sets <code>value</code> as the attribute value for BalancePcs.
     * @param value value to set the BalancePcs
     */
    public void setBalancePcs(Number value) {
        setAttributeInternal(BALANCEPCS, value);
    }

    /**
     * Gets the attribute value for AssignedPcs, using the alias name AssignedPcs.
     * @return the AssignedPcs
     */
    public Number getAssignedPcs() {
        return (Number)getAttributeInternal(ASSIGNEDPCS);
    }

    /**
     * Sets <code>value</code> as the attribute value for AssignedPcs.
     * @param value value to set the AssignedPcs
     */
    public void setAssignedPcs(Number value) {
        setAttributeInternal(ASSIGNEDPCS, value);
    }

    /**
     * Gets the attribute value for AssignCbm, using the alias name AssignCbm.
     * @return the AssignCbm
     */
    public Number getAssignCbm() {
        return (Number)getAttributeInternal(ASSIGNCBM);
    }

    /**
     * Sets <code>value</code> as the attribute value for AssignCbm.
     * @param value value to set the AssignCbm
     */
    public void setAssignCbm(Number value) {
        setAttributeInternal(ASSIGNCBM, value);
    }

    /**
     * Gets the attribute value for PackList, using the alias name PackList.
     * @return the PackList
     */
    public Number getPackList() {
        return (Number)getAttributeInternal(PACKLIST);
    }

    /**
     * Sets <code>value</code> as the attribute value for PackList.
     * @param value value to set the PackList
     */
    public void setPackList(Number value) {
        setAttributeInternal(PACKLIST, value);
    }

    /**
     * Gets the attribute value for StyleNo, using the alias name StyleNo.
     * @return the StyleNo
     */
    public String getStyleNo() {
        return (String)getAttributeInternal(STYLENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for StyleNo.
     * @param value value to set the StyleNo
     */
    public void setStyleNo(String value) {
        setAttributeInternal(STYLENO, value);
    }

    /**
     * Gets the attribute value for CurrentStyle, using the alias name CurrentStyle.
     * @return the CurrentStyle
     */
    public String getCurrentStyle() {
        return (String)getAttributeInternal(CURRENTSTYLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CurrentStyle.
     * @param value value to set the CurrentStyle
     */
    public void setCurrentStyle(String value) {
        setAttributeInternal(CURRENTSTYLE, value);
    }

    /**
     * Gets the attribute value for CurrentStyleNo, using the alias name CurrentStyleNo.
     * @return the CurrentStyleNo
     */
    public String getCurrentStyleNo() {
        return (String)getAttributeInternal(CURRENTSTYLENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for CurrentStyleNo.
     * @param value value to set the CurrentStyleNo
     */
    public void setCurrentStyleNo(String value) {
        setAttributeInternal(CURRENTSTYLENO, value);
    }

    /**
     * Gets the attribute value for SubContractOrg, using the alias name SubContractOrg.
     * @return the SubContractOrg
     */
    public Number getSubContractOrg() {
        return (Number)getAttributeInternal(SUBCONTRACTORG);
    }

    /**
     * Sets <code>value</code> as the attribute value for SubContractOrg.
     * @param value value to set the SubContractOrg
     */
    public void setSubContractOrg(Number value) {
        setAttributeInternal(SUBCONTRACTORG, value);
    }

    /**
     * Gets the attribute value for PackedCartonQty, using the alias name PackedCartonQty.
     * @return the PackedCartonQty
     */
    public Number getPackedCartonQty() {
        return (Number)getAttributeInternal(PACKEDCARTONQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for PackedCartonQty.
     * @param value value to set the PackedCartonQty
     */
    public void setPackedCartonQty(Number value) {
        setAttributeInternal(PACKEDCARTONQTY, value);
    }

    /**
     * Gets the attribute value for PackedPcsQty, using the alias name PackedPcsQty.
     * @return the PackedPcsQty
     */
    public Number getPackedPcsQty() {
        return (Number)getAttributeInternal(PACKEDPCSQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for PackedPcsQty.
     * @param value value to set the PackedPcsQty
     */
    public void setPackedPcsQty(Number value) {
        setAttributeInternal(PACKEDPCSQTY, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity InlandTransportHeaderEOImpl.
     */
    public InlandTransportHeaderEOImpl getInlandTransportHeaderEO() {
        return (InlandTransportHeaderEOImpl)getAttributeInternal(INLANDTRANSPORTHEADEREO);
    }

    /**
     * Sets <code>value</code> as the associated entity InlandTransportHeaderEOImpl.
     */
    public void setInlandTransportHeaderEO(InlandTransportHeaderEOImpl value) {
        setAttributeInternal(INLANDTRANSPORTHEADEREO, value);
    }


    /**
     * @param inlandTransLinesId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number inlandTransLinesId) {
        return new Key(new Object[]{inlandTransLinesId});
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
            super.create(attributeList);
            /* Sequence Generation Code of Header by PwC */  
            oracle.jbo.server.SequenceImpl s = new oracle.jbo.server.SequenceImpl("IEDOC_EXP_INLAND_TRAN_LINES_S",getDBTransaction());          
            oracle.jbo.domain.Number sVal = s.getSequenceNumber();          
            setInlandTransLinesId(sVal);
            /* End Sequence Generation Code of Header by PwC */
            
            
//            InlandTransportHeaderEOImpl ee = new InlandTransportHeaderEOImpl();
//             Number headerOrg = ee.getOrgId();
//             this.setSubContractOrg(headerOrg);
            
        }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
    }
}
